site_name: CMIP-Template Documentation
site_url: https://WCRP-CMIP.github.io/cmip-template-documentation/
repo_url: https://github.com/WCRP-CMIP/cmip-template-documentation
repo_name: WCRP-CMIP/cmip-template-documentation
site_description: Documentation for CMIP-Template Documentation
site_author: wolfiex

docs_dir: ../../docs
site_dir: site

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Light mode

plugins:
  - search

  - gen-files:
      scripts:
        - hooks/run_scripts.py

  - literate-nav:
      nav_file: SUMMARY.md
      implicit_index: true
      tab_length: 2

hooks:
  - hooks/generate_nav.py

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
