name: General Issue or Question
description: Report issues, ask questions, or suggest improvements
title: "[EMD] General Issue:"
labels: ['question']
body:
  - type: markdown
    attributes:
      value: |
        ## General Issue Report
        
        Report issues, ask questions, or request features for the EMD repository.

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What kind of issue are you reporting?
      options:
        - "No options available"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: affected_areas
    attributes:
      multiple: true
      label: Affected Areas
      description: |
        Which parts of EMD does this issue affect?
        
        *Select multiple if applicable*
      options:
        - "No options available"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Provide a clear and detailed description of the issue.
        
        For bugs: What happened? What did you expect?
        For features: What would you like added/changed?
      placeholder: "Describe your issue in detail..."
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected/Desired Behavior
      description: What should happen instead? What would you like to see?
      placeholder: "The system should..."

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce (for bugs)
      description: If reporting a bug, provide step-by-step instructions to reproduce.
      placeholder: "1. Go to...\n2. Click on...\n3. See error..."

  - type: markdown
    attributes:
      value: |
        ## Metadata

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this issue?
      options:
        - "No options available"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: help_needed
    attributes:
      multiple: true
      label: Help Needed
      description: Do you need help with this issue?
      options:
        - "No options available"
