name: "Stage 1: Grid Cells & Subgrid"
description: Register grid cells and subgrid (Stage 1 of 4)
title: "[EMD] Grid Cells & Subgrid:"
labels: ['emd-submission', 'c+s', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Stage 1: Grid Cells & Subgrid
        
        Creates **two linked entities**: grid cells (physical properties) and subgrid (variable locations).
        
        **Prerequisites:** None — this is the first step.
        
        > [!NOTE]
        > Please ensure you are familiar with the completion guidance in the collapsible dropdown where it exists. Failure to do so will result in a failed submission.
        > To modify an existing entry, see __[modifying entries](https://github.com/WCRP-CMIP/Essential-Model-Documentation/tree/production?tab=contributing-ov-file#2-modifying-or-reusing-existing-entries)__.
        
        [![Workflow](https://mermaid.ink/svg/pako:eNq9Vgtv2jAQ_iuWUacNJTySAG2kbep4tRJoVWGbtjEhkxhi1bGjxGlLH_995wRYWlrWVt0sJbF9r893vtxdY0_6FLt4zuWFF5BYocHpRKBs7O2ho-P-0QCeMTpEo_Fhv-uidkDEgiIVUJSoJaeIqGwxk0rJECmJArYIODyqoOhzpJgUiYtGiixo3ci_loGGvdXcXn0dLbWWTNLZIiZRsBL7OcHlcjZF9XJ5gn-t-fQYaXI_Zj5qU84T9AaNtDTzC3xU-I-rtwrqrS31Pouppw-Bxp_umLUIyB3JmF1JoQhH_bsmc54Z8HylsWLeNsdjoIa9DNAQIsRRj4SML5-MqjsagnAXAgqHWyaKhisN9-Tb2kZbhpEUVKhtnp0OswsOs7fjock5-I2Bp2p2Cpqdbc3OWvPj-kZ1ZJofbhalUslACbxvdKQ2VItkZC8n2H_2Z9n--f19O2eXYs4W6LgDNGdNA1cjswLUeeY8k_lFaru3TbSLQD3OvDMNd4IDpaLErVYXTAXprOLJsPqtfXpitofHJ9VukoADGeFmdnKzI700hB2io19lSZLSpCroxUeIdcSJou_13Z96kAtTIvxpkidDZRmC19B0xok4u4cBnPLqIIJNYkxBVZTmrLD6K5jZ64M5X2XgM6HYr48k1HwZjCwvdll3_pH1HTb1lf5HR87zYIdtSJj_a7pQpTrd3uGXwRhK3fdBd7T5NWVlLq9AsIjlGXVLtm0b-dy8YL4KXCu6NOaMc1dARB8QtV4kOuy93KL9clHnGaIPtgsm6vpMNwYsQZwJqvsCL-8cNu0Begtx1YFDMlVoLmMkCs3Du53ur9WaTc-7i8wuIsMGDmkcEuZDd3Od4cTQpoR0gl2Y-nROUg71aCJugZWkSo6WwsOuilNq4FimiwC7c8ITWKWRD7eowwhUqHCzq_8aG36oPjRuy1Qo7DbqBo6I-CFluKbDErvX-BK7VrNiW61GrdWyWlbTqrdsAy9hu7ZfaTkHMGp2w2k2Dhq3Br7KNNQq-62GgSn4U8bDvF3Lurbb3ySwHI0)](https://github.com/WCRP-CMIP/Essential-Model-Documentation/tree/main?tab=readme-ov-file#submitting-emd)
        
        > [!TIP]
        > **Reuse existing grid cells:** If a suitable grid cell definition already exists, you can reuse it by creating only a new subgrid entry. Use the prefill links below to view and copy existing grid cell configurations.
        >
        > <details><summary>Existing Grid Cells</summary>
        >
        > {existing_grid_cells}
        >
        > </details>

  - type: markdown
    attributes:
      value: |
        ---
        
        ### Grid Cell Definition
        
        Define the physical grid structure (cell arrangement, resolution, extent).

  - type: dropdown
    id: grid_type
    attributes:
      label: Grid Type
      description: |
        The cell distribution pattern that defines how grid cells are arranged across the domain.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Cell distribution pattern**
        
        Defines how grid cells are arranged across the domain.
        
        - **regular-latitude-longitude**: Uniform spacing in lat/lon
        - **reduced-gaussian**: Fewer points near poles (spectral models)
        - **tripolar**: North Pole singularity moved onto land (ocean models)
        - **displaced-pole**: Single rotated pole
        - **icosahedral**: Quasi-uniform spherical coverage
        - **cubed-sphere**: Six cube faces projected onto sphere
        - **adaptive-mesh**: Dynamically refined regions
        
        See [CF Conventions grid mappings](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#appendix-grid-mappings) for details.
        
        </details>
      options:
        - "Not specified"
        - "unstructured_polygonal"
        - "quadratic_spectral_gaussian"
        - "unstructured"
        - "hierarchical_discrete_global_grid"
        - "rotated_pole"
        - "displaced_pole"
        - "regular_gaussian"
        - "spectral_reduced_gaussian"
        - "unstructured_quadrilateral"
        - "icosahedral_geodesic_dual"
        - "tripolar"
        - "cubic_octahedral_spectral_reduced_gaussian"
        - "icosahedral_geodesic"
        - "icosahedral"
        - "yin_yang"
        - "cubed_sphere"
        - "linear_spectral_gaussian"
        - "unstructured_triangular"
        - "reduced_gaussian"
        - "spectral_gaussian"
        - "stretched"
        - "regular_latitude_longitude"
        - "plane_projection"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: grid_mapping
    attributes:
      label: Coordinate System
      description: |
        The reference coordinate system used for cell positions.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Coordinate reference system**
        
        Defines how cell positions are located.
        
        - **latitude-longitude**: Standard geographic coordinates
        - **rotated-latitude-longitude**: Pole moved to reduce distortion over region of interest
        - **stereographic**: Polar projection (polar regions)
        - **lambert-conformal**: Mid-latitude regional projection
        
        </details>
      options:
        - "Not specified"
        - "albers_conical_equal_area"
        - "polar_stereographic"
        - "vertical_perspective"
        - "rotated_latitude_longitude"
        - "transverse_mercator"
        - "lambert_conformal_conic"
        - "azimuthal_equidistant"
        - "lambert_azimuthal_equal_area"
        - "healpix"
        - "lambert_cylindrical_equal_area"
        - "geostationary"
        - "mercator"
        - "latitude_longitude"
        - "sinusoidal"
        - "orthographic"
        - "stereographic"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: region
    attributes:
      multiple: true
      label: Region
      description: |
        The geographic coverage area of the grid.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Geographic coverage**
        
        - **global**: Full Earth coverage
        - **regional**: Limited area domain
        - **arctic/antarctic**: Polar-focused domains
        - **tropical**: Equatorial band
        
        Select multiple if the grid covers distinct regions.
        
        </details>
      options:
        - "northern_hemisphere"
        - "30s-90s"
        - "tropics"
        - "greenland"
        - "antarctica"
        - "shem"
        - "southern_hemisphere"
        - "arctic"
        - "global"
        - "limited-area"
    validations:
      required: true

  - type: dropdown
    id: temporal_refinement
    attributes:
      label: Temporal Refinement
      description: |
        Whether the grid changes over time during the simulation.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Time variation of grid**
        
        - **static**: Grid remains fixed throughout simulation
        - **adaptive**: Grid changes during runtime (adaptive mesh refinement)
        
        Most grids are static.
        
        </details>
      options:
        - "Not specified"
        - "static"
        - "adaptive"
        - "dynamically_stretched"
      default: 0
    validations:
      required: true

  - type: input
    id: x_resolution
    attributes:
      label: X Resolution
      description: |
        The nominal cell size in the x-direction.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Zonal (x-direction) resolution**
        
        Nominal cell size. For spectral grids, use equivalent grid spacing.
        
        **Leave blank if:** Resolution varies by more than 25% across the domain.
        
        </details>
      placeholder: "1.25"

  - type: input
    id: y_resolution
    attributes:
      label: Y Resolution
      description: |
        The nominal cell size in the y-direction.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Meridional (y-direction) resolution**
        
        Nominal cell size.
        
        **Leave blank if:** Resolution varies by more than 25% across the domain.
        
        </details>
      placeholder: "0.9"

  - type: dropdown
    id: units
    attributes:
      label: Units
      description: The units used for resolution values.
      options:
        - "Not specified"
        - "degree"
        - "meter"
        - "km"
        - "k"
        - "pa"
      default: 0

  - type: input
    id: n_cells
    attributes:
      label: Number of Cells
      description: |
        The total number of grid cells in the domain.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Total cell count**
        
        Number of cells in the horizontal grid.
        
        For reduced grids, count actual cells (not full Gaussian equivalent).
        
        </details>
      placeholder: "55296"

  - type: input
    id: southernmost_latitude
    attributes:
      label: Southernmost Latitude
      description: |
        The southern boundary of the grid in degrees north.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Domain southern boundary**
        
        In degrees north (-90 to 90).
        
        For global grids with shifted pole, give latitude of southernmost cell center.
        
        </details>
      placeholder: "-89.5"

  - type: input
    id: westernmost_longitude
    attributes:
      label: Westernmost Longitude
      description: |
        The western boundary of the grid in degrees east.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Domain western boundary**
        
        In degrees east (0 to 360).
        
        For global grids, typically 0 or first cell center longitude.
        
        </details>
      placeholder: "0.5"

  - type: dropdown
    id: truncation_method
    attributes:
      label: Truncation Method
      description: |
        The spectral truncation type for spectral grids only.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Spectral truncation type** (spectral grids only)
        
        - **triangular**: T truncation (most common, e.g., T127)
        - **rhomboidal**: R truncation
        - **linear**: L truncation (linear grid)
        
        **Leave blank if:** Not a spectral grid.
        
        </details>
      options:
        - "Not specified"
        - "rhomboidal"
        - "triangular"
      default: 0

  - type: input
    id: truncation_number
    attributes:
      label: Truncation Number
      description: |
        The maximum wavenumber retained for spectral grids only.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Maximum wavenumber** (spectral grids only)
        
        Example: 127 for T127 truncation.
        
        **Leave blank if:** Not a spectral grid.
        
        </details>
      placeholder: "127"

  - type: markdown
    attributes:
      value: |
        ---
        
        ### Subgrid Definition
        
        Define where variables are stored on this grid. 
        
        > [!NOTE]
        > **Grid cells only?** If you only need a grid cell entry without a subgrid, select **'No subgrid (grid cells only)'** below and leave the Variable Types field empty.

  - type: dropdown
    id: subgrid_option
    attributes:
      label: Subgrid Option
      description: Whether to create a subgrid entry alongside the grid cells.
      options:
        - "Not specified"
        - "Create new subgrid"
        - "No subgrid (grid cells only)"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: cell_variable_type
    attributes:
      multiple: true
      label: Variable Types
      description: |
        The types of variables stored at this subgrid location. Leave empty if creating grid cells only.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Variable types at this subgrid location**
        
        Defines what variables are stored at these cell positions.
        
        - **mass**: Scalars (temperature, pressure, tracers)
        - **zonal-velocity**: U-component of velocity
        - **meridional-velocity**: V-component of velocity
        - **vorticity**: For spectral vorticity-divergence formulations
        - **divergence**: For spectral vorticity-divergence formulations
        
        Staggered grids (Arakawa B/C/D/E) need multiple subgrids with different variable types.
        
        </details>
      options:
        - "velocity"
        - "x-velocity"
        - "vorticity"
        - "y-velocity"
        - "mass"

  - type: markdown
    attributes:
      value: |
        ---
        
        ## Issue Handling
        
        **After submission:**
        - Creates `horizontal_grid_cells` (g###) and optionally `horizontal_subgrid` (s###)
        - Use the s### ID in Stage 2a (Horizontal Grid)
        - Track progress in issue comments

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Whether this is a new submission or a modification to an existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
