name: "Stage 1: Grid Cells & Subgrid"
description: Register grid cells and subgrid (Stage 1 of 4)
title: "[EMD] Grid Cells & Subgrid:"
labels: ['emd-submission', 'grid', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Stage 1: Grid Cells & Subgrid
        
        Creates **two linked entities**: grid cells (physical properties) and subgrid (variable locations).
        
        **Prerequisites:** None — this is the first step.
        
        ![Workflow](https://mermaid.ink/svg/pako:eNq9Vgtv2jAQ_iuWUacNJTySAG2kbep4tRJoVWGbtjEhkxhi1bGjxGlLH_995wRYWlrWVt0sJbF9r893vtxdY0_6FLt4zuWFF5BYocHpRKBs7O2ho-P-0QCeMTpEo_Fhv-uidkDEgiIVUJSoJaeIqGwxk0rJECmJArYIODyqoOhzpJgUiYtGiixo3ci_loGGvdXcXn0dLbWWTNLZIiZRsBL7OcHlcjZF9XJ5gn-t-fQYaXI_Zj5qU84T9AaNtDTzC3xU-I-rtwrqrS31Pouppw-Bxp_umLUIyB3JmF1JoQhH_bsmc54Z8HylsWLeNsdjoIa9DNAQIsRRj4SML5-MqjsagnAXAgqHWyaKhisN9-Tb2kZbhpEUVKhtnp0OswsOs7fjock5-I2Bp2p2Cpqdbc3OWvPj-kZ1ZJofbhalUslACbxvdKQ2VItkZC8n2H_2Z9n--f19O2eXYs4W6LgDNGdNA1cjswLUeeY8k_lFaru3TbSLQD3OvDMNd4IDpaLErVYXTAXprOLJsPqtfXpitofHJ9VukoADGeFmdnKzI700hB2io19lSZLSpCroxUeIdcSJou_13Z96kAtTIvxpkidDZRmC19B0xok4u4cBnPLqIIJNYkxBVZTmrLD6K5jZ64M5X2XgM6HYr48k1HwZjCwvdll3_pH1HTb1lf5HR87zYIdtSJj_a7pQpTrd3uGXwRhK3fdBd7T5NWVlLq9AsIjlGXVLtm0b-dy8YL4KXCu6NOaMc1dARB8QtV4kOuy93KL9clHnGaIPtgsm6vpMNwYsQZwJqvsCL-8cNu0Begtx1YFDMlVoLmMkCs3Du53ur9WaTc-7i8wuIsMGDmkcEuZDd3Od4cTQpoR0gl2Y-nROUg71aCJugZWkSo6WwsOuilNq4FimiwC7c8ITWKWRD7eowwhUqHCzq_8aG36oPjRuy1Qo7DbqBo6I-CFluKbDErvX-BK7VrNiW61GrdWyWlbTqrdsAy9hu7ZfaTkHMGp2w2k2Dhq3Br7KNNQq-62GgSn4U8bDvF3Lurbb3ySwHI0)
        
        > [!NOTE]
        > Please read the guidance (▶) before filling in — incorrect entries will be rejected.
        > To modify an existing entry, check the [grid files](https://github.com/WCRP-CMIP/Essential-Model-Documentation/tree/main/horizontal_grid_cells).

  - type: dropdown
    id: grid_type
    attributes:
      label: Grid Type
      description: |
        Cell distribution pattern.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Cell distribution pattern**
        
        Defines how grid cells are arranged across the domain.
        
        - **regular-latitude-longitude**: Uniform spacing in lat/lon
        - **reduced-gaussian**: Fewer points near poles (spectral models)
        - **tripolar**: North Pole singularity moved onto land (ocean models)
        - **displaced-pole**: Single rotated pole
        - **icosahedral**: Quasi-uniform spherical coverage
        - **cubed-sphere**: Six cube faces projected onto sphere
        - **adaptive-mesh**: Dynamically refined regions
        
        See [CF Conventions grid mappings](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#appendix-grid-mappings) for details.
        
        </details>
      options:
        - "Not specified"
        - "regular-latitude-longitude"
        - "reduced-gaussian"
        - "tripolar"
        - "displaced-pole"
        - "icosahedral"
        - "cubed-sphere"
        - "adaptive-mesh"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: grid_mapping
    attributes:
      label: Coordinate System
      description: |
        Reference system for cell positions.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Coordinate reference system**
        
        Defines how cell positions are located.
        
        - **latitude-longitude**: Standard geographic coordinates
        - **rotated-latitude-longitude**: Pole moved to reduce distortion over region of interest
        - **stereographic**: Polar projection (polar regions)
        - **lambert-conformal**: Mid-latitude regional projection
        
        </details>
      options:
        - "Not specified"
        - "latitude-longitude"
        - "rotated-latitude-longitude"
        - "stereographic"
        - "lambert-conformal"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: region
    attributes:
      multiple: true
      label: Region
      description: |
        Geographic coverage of the grid.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Geographic coverage**
        
        - **global**: Full Earth coverage
        - **regional**: Limited area domain
        - **arctic/antarctic**: Polar-focused domains
        - **tropical**: Equatorial band
        
        Select multiple if the grid covers distinct regions.
        
        </details>
      options:
        - "global"
        - "regional"
        - "arctic"
        - "antarctic"
        - "tropical"
    validations:
      required: true

  - type: dropdown
    id: temporal_refinement
    attributes:
      label: Temporal Refinement
      description: |
        Whether the grid changes over time.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Time variation of grid**
        
        - **static**: Grid remains fixed throughout simulation
        - **adaptive**: Grid changes during runtime (adaptive mesh refinement)
        
        Most grids are static.
        
        </details>
      options:
        - "Not specified"
        - "static"
        - "adaptive"
      default: 0
    validations:
      required: true

  - type: input
    id: x_resolution
    attributes:
      label: X Resolution
      description: |
        Nominal cell size in x-direction.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Zonal (x-direction) resolution**
        
        Nominal cell size. For spectral grids, use equivalent grid spacing.
        
        **Leave blank if:** Resolution varies by more than 25% across the domain.
        
        </details>
      placeholder: "1.25"

  - type: input
    id: y_resolution
    attributes:
      label: Y Resolution
      description: |
        Nominal cell size in y-direction.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Meridional (y-direction) resolution**
        
        Nominal cell size.
        
        **Leave blank if:** Resolution varies by more than 25% across the domain.
        
        </details>
      placeholder: "0.9"

  - type: dropdown
    id: units
    attributes:
      label: Units
      description: Resolution units.
      options:
        - "Not specified"
        - "degree"
        - "km"
        - "m"
      default: 0

  - type: input
    id: n_cells
    attributes:
      label: Number of Cells
      description: |
        Total number of grid cells.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Total cell count**
        
        Number of cells in the horizontal grid.
        
        For reduced grids, count actual cells (not full Gaussian equivalent).
        
        </details>
      placeholder: "55296"

  - type: input
    id: southernmost_latitude
    attributes:
      label: Southernmost Latitude
      description: |
        Southern boundary in degrees north.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Domain southern boundary**
        
        In degrees north (-90 to 90).
        
        For global grids with shifted pole, give latitude of southernmost cell center.
        
        </details>
      placeholder: "-89.5"

  - type: input
    id: westernmost_longitude
    attributes:
      label: Westernmost Longitude
      description: |
        Western boundary in degrees east.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Domain western boundary**
        
        In degrees east (0 to 360).
        
        For global grids, typically 0 or first cell center longitude.
        
        </details>
      placeholder: "0.5"

  - type: dropdown
    id: truncation_method
    attributes:
      label: Truncation Method
      description: |
        Spectral truncation type (spectral grids only).
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Spectral truncation type** (spectral grids only)
        
        - **triangular**: T truncation (most common, e.g., T127)
        - **rhomboidal**: R truncation
        - **linear**: L truncation (linear grid)
        
        **Leave blank if:** Not a spectral grid.
        
        </details>
      options:
        - "Not specified"
        - "triangular"
        - "rhomboidal"
        - "linear"
      default: 0

  - type: input
    id: truncation_number
    attributes:
      label: Truncation Number
      description: |
        Maximum wavenumber (spectral grids only).
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Maximum wavenumber** (spectral grids only)
        
        Example: 127 for T127 truncation.
        
        **Leave blank if:** Not a spectral grid.
        
        </details>
      placeholder: "127"

  - type: dropdown
    id: cell_variable_type
    attributes:
      multiple: true
      label: Variable Types
      description: |
        Types of variables stored at this subgrid location.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Variable types at this subgrid location**
        
        Defines what variables are stored at these cell positions.
        
        - **mass**: Scalars (temperature, pressure, tracers)
        - **zonal-velocity**: U-component of velocity
        - **meridional-velocity**: V-component of velocity
        - **vorticity**: For spectral vorticity-divergence formulations
        - **divergence**: For spectral vorticity-divergence formulations
        
        Staggered grids (Arakawa B/C/D/E) need multiple subgrids with different variable types.
        
        </details>
      options:
        - "mass"
        - "zonal-velocity"
        - "meridional-velocity"
        - "vorticity"
        - "divergence"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        ## Issue Handling
        
        **After submission:**
        - Creates `horizontal_grid_cells` (g###) and `horizontal_subgrid` (s###)
        - Use the s### ID in Stage 2a (Horizontal Grid)
        - [Track progress in your issues](https://github.com/WCRP-CMIP/Essential-Model-Documentation/issues?q=is%3Aissue%20state%3Aopen%20author%3A%40me)

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: New submission or modification.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
