name: "Add/Modify: Horizontal Grid Cells"
description: Register horizontal grid cell properties
title: "Add/Modify: Horizontal Grid Cells: <Type grid cells ID here>"
labels: ['emd-submission', 'horizontal-grid', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Horizontal Grid Cells Registration
        
        Register horizontal grid cell properties.
        
        Defines the physical characteristics and location of grid cells.
        
        Grid cell IDs follow format: g[NNN] (e.g., g100, g101)

  - type: input
    id: id
    attributes:
      label: Grid Cells ID
      description: |
        Unique identifier for this grid cells definition.
        
        Format: g[NNN] where NNN is a number.
      placeholder: "e.g., g100, g101, g102"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Description to distinguish these grid cells from similar ones.
        
        Include key characteristics like resolution and domain.
      placeholder: "e.g., Global regular lat-lon grid with 1.25° x 0.9° resolution"
    validations:
      required: true

  - type: dropdown
    id: grid_type
    attributes:
      label: Grid Type
      description: |
        How cells are distributed over the region.
        
        - regular-latitude-longitude: Uniform lat-lon spacing
        - reduced-gaussian: Gaussian with varying longitudinal points
        - linear-spectral-gaussian: Spectral transform grid
        - tripolar: Three-pole ocean grid
        - cubed-sphere: Cube projected onto sphere
        - unstructured-polygon: Irregular mesh
        - plane-projection: Projected coordinate grid
      options:
        - "cubed_sphere"
        - "cubic_octahedral_spectral_reduced_gaussian"
        - "displaced_pole"
        - "hierarchical_discrete_global_grid"
        - "icosahedral"
        - "icosahedral_geodesic"
        - "icosahedral_geodesic_dual"
        - "linear_spectral_gaussian"
        - "plane_projection"
        - "quadratic_spectral_gaussian"
        - "reduced_gaussian"
        - "regular_gaussian"
        - "regular_latitude_longitude"
        - "rotated_pole"
        - "spectral_gaussian"
        - "spectral_reduced_gaussian"
        - "stretched"
        - "tripolar"
        - "unstructured"
        - "unstructured_polygonal"
        - "unstructured_quadrilateral"
        - "unstructured_triangular"
        - "yin_yang"
    validations:
      required: true

  - type: dropdown
    id: grid_mapping
    attributes:
      label: Grid Mapping
      description: |
        Coordinate reference system.
        
        - latitude-longitude: Standard spherical coordinates
        - rotated-latitude-longitude: Rotated pole coordinates
        - polar-stereographic: Polar projection
        - lambert-conformal-conic: Lambert projection
      options:
        - "albers_conical_equal_area"
        - "azimuthal_equidistant"
        - "geostationary"
        - "healpix"
        - "lambert_azimuthal_equal_area"
        - "lambert_conformal_conic"
        - "lambert_cylindrical_equal_area"
        - "latitude_longitude"
        - "mercator"
        - "orthographic"
        - "polar_stereographic"
        - "rotated_latitude_longitude"
        - "sinusoidal"
        - "stereographic"
        - "transverse_mercator"
        - "vertical_perspective"
    validations:
      required: true

  - type: dropdown
    id: region
    attributes:
      multiple: true
      label: Region
      description: |
        Geographic region(s) covered by the grid.
        
        - global: Whole Earth
        - antarctica: Antarctic region
        - greenland: Greenland region
        - limited-area: Regional model domain
      options:
        - "30s-90s"
        - "antarctica"
        - "arctic"
        - "global"
        - "greenland"
        - "limited-area"
        - "northern_hemisphere"
        - "shem"
        - "southern_hemisphere"
        - "tropics"
    validations:
      required: true

  - type: dropdown
    id: temporal_refinement
    attributes:
      label: Temporal Refinement
      description: |
        How the grid varies with time.
        
        - static: Fixed grid
        - adaptive: Mesh refinement
        - dynamically-stretched: Moving mesh
      options:
        - "adaptive"
        - "dynamically_stretched"
        - "static"
    validations:
      required: true

  - type: input
    id: x_resolution
    attributes:
      label: X Resolution
      description: |
        Cell size in X direction (longitude for spherical).
        
        Omit if varies more than 25%.
      placeholder: "e.g., 1.25"

  - type: input
    id: y_resolution
    attributes:
      label: Y Resolution
      description: |
        Cell size in Y direction (latitude for spherical).
        
        Omit if varies more than 25%.
      placeholder: "e.g., 0.9"

  - type: dropdown
    id: units
    attributes:
      label: Units
      description: |
        Physical units for resolution values.
        
        Required if x_resolution or y_resolution is provided.
      options:
        - "Not applicable"
        - "degree"
        - "k"
        - "km"
        - "meter"
        - "pa"

  - type: input
    id: n_cells
    attributes:
      label: Number of Cells
      description: |
        Total number of horizontal cells.
        
        Leave blank if variable (e.g., adaptive grids).
      placeholder: "e.g., 55296"

  - type: input
    id: southernmost_latitude
    attributes:
      label: Southernmost Latitude
      description: |
        Southernmost latitude in degrees north.
        
        Must be -90 to 90. Leave blank if not applicable.
      placeholder: "e.g., -89.5"

  - type: input
    id: westernmost_longitude
    attributes:
      label: Westernmost Longitude
      description: |
        Westernmost longitude in degrees east.
        
        Must be 0 to <360. Leave blank if not applicable.
      placeholder: "e.g., 0.5"

  - type: markdown
    attributes:
      value: |
        ### Spectral Grid Options
        
        Only for spectral/Gaussian grids:

  - type: dropdown
    id: truncation_method
    attributes:
      label: Truncation Method
      description: |
        Method for truncating spherical harmonics.
        
        Only applicable for spectral models.
      options:
        - "Not applicable"
        - "rhomboidal"
        - "triangular"

  - type: input
    id: truncation_number
    attributes:
      label: Truncation Number
      description: |
        Zonal wave number for spectral truncation.
        
        Only applicable for spectral models.
      placeholder: "e.g., 127"

  - type: markdown
    attributes:
      value: |
        ## Issue Handling Metadata

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
