name: Horizontal Grid Properties Documentation
description: Document horizontal grid specifications as compound objects for EMD compliance.
title: "[EMD] Horizontal Grid Properties"
labels: ['emd-submission', 'horizontal-grid']
body:
  - type: markdown
    attributes:
      value: |
        # Horizontal Grid Properties Documentation
        
        This template documents horizontal grid specifications as compound objects referenced by model components. Based on EMD Section 4.1 requirements.

  - type: dropdown
    id: grid
    attributes:
      label: Grid
      description: |
        The horizontal grid type.
        
        MANDATORY field from Native horizontal grid Type CV.
      options:
        - "no-horizontal-grid"
        - "cubed-sphere"
        - "cubic-octahedral-spectral-reduced-gaussian"
        - "displaced-pole"
        - "icosahedral-geodesic-dual"
        - "icosahedral-geodesic"
        - "linear-spectral-gaussian"
        - "no-grid"
        - "plane-projection"
        - "quadratic-spectral-gaussian"
        - "reduced-gaussian"
        - "regular-gaussian"
        - "regular-latitude-longitude"
        - "rotated-pole"
        - "spectral-gaussian"
        - "spectral-reduced-gaussian"
        - "stretched"
        - "tripolar"
        - "unstructured-polygonal"
        - "unstructured-triangular"
        - "yin-yang"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description (Optional)
      description: |
        Free-text description of the horizontal grid.
        
        OPTIONAL field.
      placeholder: "Additional horizontal grid details if needed"

  - type: dropdown
    id: grid_mapping
    attributes:
      label: Grid Mapping
      description: |
        The coordinate reference system of the horizontal coordinates.
        
        MANDATORY field from Grid Mapping CV.
      options:
        - "albers_conical_equal_area"
        - "azimuthal_equidistant"
        - "geostationary"
        - "lambert_azimuthal_equal_area"
        - "lambert_conformal_conic"
        - "lambert_cylindrical_equal_area"
        - "latitude_longitude"
        - "orthographic"
        - "polar_stereographic"
        - "rotated_latitude_longitude"
        - "sinusoidal"
        - "stereographic"
        - "transverse_mercator"
        - "vertical_perspective"
    validations:
      required: true

  - type: dropdown
    id: region
    attributes:
      label: Region
      description: |
        The portion of the globe where calculations are performed.
        
        MANDATORY field from Region CV.
      options:
        - "antarctica"
        - "global"
        - "greenland"
        - "limited-area"
    validations:
      required: true

  - type: dropdown
    id: temporal_refinement
    attributes:
      label: Temporal Refinement
      description: |
        How the distribution of grid cells varies with time.
        
        MANDATORY field from Temporal refinement CV.
      options:
        - "adaptive"
        - "dynamically-stretched"
        - "static"
    validations:
      required: true

  - type: dropdown
    id: arrangement
    attributes:
      label: Arrangement
      description: |
        Grid arrangement of orthogonal physical quantities.
        
        MANDATORY field from Arrangement CV.
      options:
        - "arakawa_A"
        - "arakawa_B"
        - "arakawa_C"
        - "arakawa_D"
        - "arakawa_E"
    validations:
      required: true

  - type: input
    id: resolution_x
    attributes:
      label: Resolution X
      description: |
        Horizontal resolution in X direction.
        
        OPTIONAL float field.
      placeholder: "e.g., 1.25"

  - type: input
    id: resolution_y
    attributes:
      label: Resolution Y
      description: |
        Horizontal resolution in Y direction.
        
        OPTIONAL float field.
      placeholder: "e.g., 0.9375"

  - type: dropdown
    id: horizontal_units
    attributes:
      label: Horizontal Units
      description: |
        Units for resolution_x and resolution_y.
        
        OPTIONAL field - Required if resolution_x or resolution_y are set.
      options:
        - "degrees"
        - "km"
        - "m"

  - type: input
    id: n_cells
    attributes:
      label: N Cells
      description: |
        Total number of grid cells.
        
        MANDATORY integer field.
      placeholder: "e.g., 139968"
    validations:
      required: true

  - type: input
    id: n_sides
    attributes:
      label: N Sides
      description: |
        Number of cell sides for unstructured grids.
        
        OPTIONAL integer field.
      placeholder: "e.g., 714274"

  - type: input
    id: n_vertices
    attributes:
      label: N Vertices
      description: |
        Number of vertices for unstructured grids.
        
        OPTIONAL integer field.
      placeholder: "e.g., 567145"

  - type: dropdown
    id: truncation_method
    attributes:
      label: Truncation Method
      description: |
        Method for truncating spherical harmonic expansion.
        
        OPTIONAL field from Truncation method CV.
      options:
        - "triangular"
        - "rhomboidal"

  - type: input
    id: truncation_number
    attributes:
      label: Truncation Number
      description: |
        Truncation number for spectral grids.
        
        OPTIONAL integer field.
      placeholder: "e.g., 63"

  - type: input
    id: resolution_range_km
    attributes:
      label: Resolution Range (km)
      description: |
        Minimum and maximum resolution in km.
        
        MANDATORY field as [float,float].
        
        Format: min, max
      placeholder: "e.g., 57.0, 290"
    validations:
      required: true

  - type: input
    id: mean_resolution_km
    attributes:
      label: Mean Resolution (km)
      description: |
        Mean resolution in km.
        
        MANDATORY float field.
      placeholder: "e.g., 234.5"
    validations:
      required: true

  - type: dropdown
    id: nominal_resolution
    attributes:
      label: Nominal Resolution
      description: |
        Nominal resolution characterizing the grid.
        
        MANDATORY field from Nominal resolution CV.
      options:
        - "0.5 km"
        - "10000 km"
        - "1000 km"
        - "100 km"
        - "10 km"
        - "1 km"
        - "1x1 degree"
        - "2.5 km"
        - "2500 km"
        - "250 km"
        - "25 km"
        - "5000 km"
        - "500 km"
        - "50 km"
        - "5 km"
    validations:
      required: true

  - type: dropdown
    id: issue_category
    attributes:
      label: Issue Type
      description: This is pre-set and cannot be changed.
      options:
        - "horizontal-grid"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "new"
        - "modify"
      default: 0
    validations:
      required: true
