name: "Add/Modify: Horizontal Computational Grid"
description: Register a horizontal computational grid
title: "Add/Modify: Horizontal Computational Grid: <Type grid ID here>"
labels: ['emd-submission', 'horizontal-grid', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Horizontal Computational Grid Registration
        
        Register a horizontal computational grid definition.
        
        A computational grid is composed of one or more horizontal subgrids on which different variables are calculated.
        
        Grid IDs follow format: c[NNN] (e.g., c100, c101)

  - type: input
    id: id
    attributes:
      label: Grid ID
      description: |
        Unique identifier for this grid.
        
        Format: c[NNN] where NNN is a number.
      placeholder: "e.g., c100, c101, c102"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Description to distinguish this grid from similar ones.
        
        Include key characteristics like target use (atmosphere, ocean, etc.).
      placeholder: "e.g., Arakawa-C grid for atmospheric modelling with TL127 spectral transform"
    validations:
      required: true

  - type: dropdown
    id: arrangement
    attributes:
      label: Arrangement
      description: |
        Grid staggering arrangement.
        
        Defines relative positions of mass-related and velocity-related variables.
        
        - arakawa-a: Mass and velocity at same location
        - arakawa-b: Velocity at corners of mass cells
        - arakawa-c: Velocity at edge centers, perpendicular to edge
        - arakawa-d: Velocity at edge centers, tangential to edge
        - arakawa-e: Mass at velocity cell edge centers
      options:
        - "arakawa-a"
        - "arakawa-b"
        - "arakawa-c"
        - "arakawa-d"
        - "arakawa-e"
    validations:
      required: true

  - type: input
    id: horizontal_subgrids
    attributes:
      label: Horizontal Subgrids
      description: |
        Semicolon-separated list of subgrid IDs that comprise this computational grid.
        
        Subgrids must be registered via the Horizontal Subgrid template.
      placeholder: "e.g., s100;s101 or s100"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Issue Handling Metadata

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
