name: "Stage 2a: Horizontal Computational Grid"
description: Register horizontal computational grid (Stage 2a of 4)
title: "[EMD] Horizontal Grid:"
labels: ['emd-submission', 'grid', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Stage 2a: Horizontal Computational Grid
        
        Links subgrids into a single computational grid with a specified staggering arrangement.
        
        **Prerequisites:** Subgrid IDs (s###) from Stage 1.
        
        ```mermaid
        flowchart LR
            subgraph Stage1[\**Stage 1**\"]
                S1[\"Grid Cells & Subgrid\"]
            end
            subgraph Stage2[\"**Stage 2**\"]
                direction TB
                S2a[\"Horizontal Grid\"]
                S2b[\"Vertical Grid\"]
            end
            subgraph MF[\"**Model Family**\"]
                direction TB
                ESM[\"Earth System Family\"]
                CF[\"Component Family\"]
            end
            subgraph Stage3[\"**Stage 3**\"]
                S3[\"Model Component\"]
            end
            subgraph Stage4[\"**Stage 4**\"]
                S4[\"Model\"]
            end
            S1 -->|g###

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Brief characterization of this computational grid.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Grid characterization**
        
        Brief description of this computational grid.
        
        **What to include:**
        1. Arrangement type (e.g., Arakawa-C)
        2. Key properties (resolution, spectral truncation)
        3. Typical use (atmosphere, ocean, etc.)
        
        **Example:** 'Arakawa-C grid combining TL127 spectral Gaussian and 1.25°×0.9° regular lat-lon subgrids for atmospheric modelling.'
        
        </details>
      placeholder: "1. Arrangement type\n2. Resolution or spectral truncation\n3. Typical use (atmosphere/ocean)"
    validations:
      required: true

  - type: dropdown
    id: arrangement
    attributes:
      label: Arrangement
      description: |
        Grid staggering pattern.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Grid staggering pattern**
        
        Defines relative positions of mass and velocity variables.
        
        - **arakawa-a / unstaggered**: All variables at same location
        - **arakawa-b**: Velocities at cell corners
        - **arakawa-c**: U at east/west edges, V at north/south edges (common for ocean)
        - **arakawa-d**: U at north/south edges, V at east/west edges
        - **arakawa-e**: Mass at edge midpoints
        
        **Number of subgrids needed:**
        - Unstaggered/A: 1 subgrid
        - B: 2 subgrids (mass + corner velocity)
        - C/D: 2-3 subgrids (mass + edge velocities)
        
        </details>
      options:
        - "Not specified"
        - "arakawa-a"
        - "arakawa-b"
        - "arakawa-c"
        - "arakawa-d"
        - "arakawa-e"
        - "unstaggered"
      default: 0
    validations:
      required: true

  - type: textarea
    id: horizontal_subgrids
    attributes:
      label: Subgrid IDs
      description: |
        Subgrid IDs from Stage 1.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Subgrid references**
        
        List the s### IDs from Stage 1.
        
        **Format:** One ID per line
        
        **Example for Arakawa-C:**
        ```
        s100
        s101
        ```
        Where s100 = mass variables, s101 = velocity variables.
        
        Number of subgrids must match your arrangement type.
        
        </details>
      placeholder: "s100\ns101"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        ## Issue Handling
        
        **After submission:**
        - Creates `horizontal_computational_grid` (c###)
        - Use this ID with a v### in Stage 3 (Model Component)
        - Track progress in issue comments

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: New submission or modification.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
