name: Horizontal Computational Grid Registration
description: Register a horizontal computational grid by linking subgrids
title: "[EMD] Horizontal Computational Grid:"
labels: ['emd-submission', 'grid', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Horizontal Computational Grid Registration
        
        Register a horizontal computational grid.
        
        **Prerequisites:** Subgrid IDs must exist (submit Grid Cells and Subgrid issue first).
        
        **This issue creates 1 entity:**
        - Horizontal computational grid (links to subgrids)
        
        **Result:** Horizontal grid ID (e.g., c100) to use when registering Model Components.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Description of this horizontal computational grid.
        
        Include key characteristics and purpose.
        
        Example: 'Arakawa-C grid for atmospheric modelling combining regular lat-lon and spectral subgrids'
        
        <details markdown="1">
        <summary>Completion Guidance</summary>
        
        **Grid description** (from EMD specification):
        
        A description is only required if there is information that is not covered by any of the other properties.
        
        **Include:**
        - Grid purpose (atmosphere, ocean, etc.)
        - Staggering type
        - Key characteristics
        - Any non-standard features
        
        **Omit when:** Not required (all info covered by other properties)
        
        </details>
      placeholder: "e.g., Arakawa-C grid for atmosphere with TL127 spectral transform and 1.25° × 0.9° resolution"
    validations:
      required: true

  - type: dropdown
    id: arrangement
    attributes:
      label: Arrangement
      description: |
        Grid staggering arrangement.
        
        Defines relative positions of mass and velocity variables.
        
        Common:
        - **arakawa-a**: Unstaggered (mass and velocity same location)
        - **arakawa-b**: Velocity at corners
        - **arakawa-c**: Velocity at edge centers, perpendicular
        - **arakawa-d**: Velocity at edge centers, tangential
        - **arakawa-e**: Mass at edge centers
        - **unstaggered**: No staggering
        
        <details markdown="1">
        <summary>Completion Guidance</summary>
        
        **Grid arrangement/staggering** (from EMD arrangement CV):
        
        A grid arrangement describes the relative locations of computed mass-related and velocity-related quantities on the horizontal computational grid.
        
        When the computational grid relies on more than one subgrid, it is referred to as a 'staggered' grid. For most staggered grids, the velocity-related variables are calculated on a subgrid offset from the mass-related variables.
        
        **Options:**
        - **arakawa_a**: Mass- and velocity-related quantities at the same location on each grid cell (unstaggered)
        - **arakawa_b**: Velocity-related quantities at the corners of mass cells
        - **arakawa_c**: Velocity-related quantities at the centres of mass cell edges, perpendicular to edge (most common for atmosphere/ocean)
        - **arakawa_d**: Velocity-related quantities at the centres of mass cell edges, tangential to edge
        - **arakawa_e**: Mass-related quantities at the centres of velocity cell edges
        
        **Match arrangement to number of subgrids:**
        - Arakawa-A (unstaggered): 1 subgrid
        - Arakawa-B: 2 subgrids (mass + velocity at corners)
        - Arakawa-C: 2-3 subgrids (mass + x_velocity + y_velocity, or mass + velocity for unstructured)
        - Complex staggering: 2+ subgrids
        
        </details>
      options:
        - "Not specified"
        - "arakawa-a"
        - "arakawa-b"
        - "arakawa-c"
        - "arakawa-d"
        - "arakawa-e"
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Subgrid References
        
        Enter the subgrid IDs you received from your Grid Cells and Subgrid issue(s).
        
        One ID per line.
        
        **Must match your arrangement:**
        - Unstaggered: 1 subgrid
        - Arakawa-C: 2 subgrids (mass + velocity)
        - Other staggered: 2+ subgrids

  - type: textarea
    id: horizontal_subgrids
    attributes:
      label: Subgrid IDs
      description: |
        Enter subgrid IDs, one per line.
        
        Example:
        s100
        s101
        
        You received these IDs when you submitted Grid Cells and Subgrid issue(s).
        
        <details markdown="1">
        <summary>Completion Guidance</summary>
        
        **Horizontal subgrids** (from EMD specification):
        
        All of the subgrids, of which there must be at least one, used to construct the horizontal computational grid.
        
        A horizontal subgrid describes the grid cells at one of the stagger positions. Often the locations of mass-related and velocity-related variables differ, so more than one horizontal subgrid will be defined.
        
        **Format:** One subgrid ID per line
        
        You received these IDs when you submitted your Grid Cells and Subgrid issue(s).
        
        **Number of subgrids must match your arrangement:**
        - Unstaggered/Arakawa-A: 1 subgrid (mass only)
        - Arakawa-B: 2 subgrids (mass + velocity)
        - Arakawa-C: 2-3 subgrids (mass + velocity components)
        
        **Order matters** for some arrangements (convention: mass subgrid first, then velocity)
        
        </details>
      placeholder: "s100\ns101"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## What Will Be Generated
        
        This issue creates:
        
        **horizontal_computational_grid** (ID: c###)
        - Links to your subgrid(s)
        - Contains: Arrangement type
        - References: Subgrid IDs you provided
        
        **You'll receive:** Horizontal grid ID (c###)
        
        **Next:** Use this ID (c###) + vertical grid ID (v###) in Model Component issue.

  - type: markdown
    attributes:
      value: |
        ## Issue Handling Metadata

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
