name: "Stage 2a: Horizontal Computational Grid"
description: Register horizontal computational grid (Stage 2a of 4)
title: "[EMD] Horizontal Grid:"
labels: ['emd-submission', 'grid', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Stage 2a: Horizontal Computational Grid
        
        Links subgrids into a single computational grid with a specified staggering arrangement.
        
        **Prerequisites:** Subgrid IDs (s###) from Stage 1.
        
        **Result:** Horizontal grid ID (c###)
        
        ![Workflow](https://mermaid.ink/svg/pako:eNq9Vgtv2jAQ_iuWUacNJTySAG2kbep4tRJoVWGbtjEhkxhi1bGjxGlLH_995wRYWlrWVt0sJbF9r893vtxdY0_6FLt4zuWFF5BYocHpRKBs7O2ho-P-0QCeMTpEo_Fhv-uidkDEgiIVUJSoJaeIqGwxk0rJECmJArYIODyqoOhzpJgUiYtGiixo3ci_loGGvdXcXn0dLbWWTNLZIiZRsBL7OcHlcjZF9XJ5gn-t-fQYaXI_Zj5qU84T9AaNtDTzC3xU-I-rtwrqrS31Pouppw-Bxp_umLUIyB3JmF1JoQhH_bsmc54Z8HylsWLeNsdjoIa9DNAQIsRRj4SML5-MqjsagnAXAgqHWyaKhisN9-Tb2kZbhpEUVKhtnp0OswsOs7fjock5-I2Bp2p2Cpqdbc3OWvPj-kZ1ZJofbhalUslACbxvdKQ2VItkZC8n2H_2Z9n--f19O2eXYs4W6LgDNGdNA1cjswLUeeY8k_lFaru3TbSLQD3OvDMNd4IDpaLErVYXTAXprOLJsPqtfXpitofHJ9VukoADGeFmdnKzI700hB2io19lSZLSpCroxUeIdcSJou_13Z96kAtTIvxpkidDZRmC19B0xok4u4cBnPLqIIJNYkxBVZTmrLD6K5jZ64M5X2XgM6HYr48k1HwZjCwvdll3_pH1HTb1lf5HR87zYIdtSJj_a7pQpTrd3uGXwRhK3fdBd7T5NWVlLq9AsIjlGXVLtm0b-dy8YL4KXCu6NOaMc1dARB8QtV4kOuy93KL9clHnGaIPtgsm6vpMNwYsQZwJqvsCL-8cNu0Begtx1YFDMlVoLmMkCs3Du4d8uKkCa3i1WrPpeXcR2kWE2MAhjUPCfOhyrjO8GNqVkE6wC1OfzknKoS5NxC2wklTJ0VJ42FVxSg0cy3QRYHdOeAKrNPLhNnUYgUoVbnb132PDD1WIxm2ZCoVdp2XgiIgfUoZrOiyxe40vsWs1K7bVatRaLatlNa16yzbwErZr-5WWcwCjZjecZuOgcWvgq0xDrbLfahiYgl9lPMzbtqx7u_0NCvweHQ)
        
        > ⚠️ **Read the guidance (▶) before filling in** — incorrect entries will be rejected. To modify an existing entry, check the [horizontal grid files](https://github.com/WCRP-CMIP/Essential-Model-Documentation/tree/main/horizontal_computational_grid).

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Brief characterization of this computational grid.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Grid characterization**
        
        Brief description of this computational grid.
        
        **What to include:**
        1. Arrangement type (e.g., Arakawa-C)
        2. Key properties (resolution, spectral truncation)
        3. Typical use (atmosphere, ocean, etc.)
        
        **Example:** 'Arakawa-C grid combining TL127 spectral Gaussian and 1.25°×0.9° regular lat-lon subgrids for atmospheric modelling.'
        
        </details>
      placeholder: "1. Arrangement type
2. Resolution or spectral truncation
3. Typical use (atmosphere/ocean)"
    validations:
      required: true

  - type: dropdown
    id: arrangement
    attributes:
      label: Arrangement
      description: |
        Grid staggering pattern.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Grid staggering pattern**
        
        Defines relative positions of mass and velocity variables.
        
        - **arakawa-a / unstaggered**: All variables at same location
        - **arakawa-b**: Velocities at cell corners
        - **arakawa-c**: U at east/west edges, V at north/south edges (common for ocean)
        - **arakawa-d**: U at north/south edges, V at east/west edges
        - **arakawa-e**: Mass at edge midpoints
        
        **Number of subgrids needed:**
        - Unstaggered/A: 1 subgrid
        - B: 2 subgrids (mass + corner velocity)
        - C/D: 2-3 subgrids (mass + edge velocities)
        
        </details>
      options:
        - "Not specified"
        - "arakawa-a"
        - "arakawa-b"
        - "arakawa-c"
        - "arakawa-d"
        - "arakawa-e"
        - "unstaggered"
      default: 0
    validations:
      required: true

  - type: textarea
    id: horizontal_subgrids
    attributes:
      label: Subgrid IDs
      description: |
        Subgrid IDs from Stage 1.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Subgrid references**
        
        List the s### IDs from Stage 1.
        
        **Format:** One ID per line
        
        **Example for Arakawa-C:**
        ```
        s100
        s101
        ```
        Where s100 = mass variables, s101 = velocity variables.
        
        Number of subgrids must match your arrangement type.
        
        </details>
      placeholder: "s100
s101"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        ## Issue Handling
        
        **After submission:**
        - Creates `horizontal_computational_grid` (c###)
        - Use this ID with a v### in Stage 3 (Model Component)
        - Track progress in issue comments

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: New submission or modification.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
