name: Model Family Registration
description: Register a model family for genealogy tracking
title: "[EMD] Model Family:"
labels: ['emd-submission', 'family', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Model Family Registration
        
        Register a model family - a group of models sharing code bases.
        
        Model families help establish model genealogies for inter-model comparisons.
        
        See [Masson and Knutti (2011)](https://doi.org/10.1029/2011GL046864) for examples.

  - type: input
    id: name
    attributes:
      label: Family Name
      description: |
        The family name.
        
        Often persists across model versions and may be the first part of full model names.
        
        <details markdown="1">
        <summary>Completion Guidance</summary>
        
        **Family name** (from EMD specification):
        
        A family of models share much of their code bases, but may be configured in different ways (e.g. different resolutions, parameter choices, or the inclusion or not of particular model components).
        
        A family name often persists across model versions and may be the first part of the model's full name.
        
        See Masson and Knutti (2011) for an example of how the family can be used to inform model genealogies.
        
        **Naming conventions:**
        - Often first part of model names
        - Use hyphens for separators
        - Typically institution/project acronym + model name
        
        **Used for:**
        - Model genealogy studies
        - Identifying related models
        - Tracking code lineage
        
        </details>
      placeholder: "e.g., HadGEM3, CESM, CNRM-CM, ACCESS"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Description of the model family.
        
        Include scientific focus and common characteristics shared by family members.
        
        <details markdown="1">
        <summary>Completion Guidance</summary>
        
        **Family description** (from EMD specification):
        
        Describe what characterizes this model family.
        
        **What to include:**
        1. **Origin**: Institution and development history
        2. **Scientific focus**: What distinguishes this family
        3. **Common features**: Shared code, physics, or approach
        4. **Variation dimensions**: How family members differ (resolution, parameters, components)
        
        **2-3 paragraphs typical**
        
        </details>
      placeholder: "Describe the model family, its scientific focus, and common characteristics..."
    validations:
      required: true

  - type: dropdown
    id: primary_institution
    attributes:
      label: Primary Institution
      description: The primary institution responsible for the model family.
      options:
        - "Not specified"
        - "awi"
        - "bcc"
        - "cccma"
        - "cmcc"
        - "cnrm-cerfacs"
        - "csiro"
        - "csiro-arccss"
        - "dkrz"
        - "ec-earth-consortium"
        - "gfdl"
        - "inpe"
        - "ipsl"
        - "miroc"
        - "mohc"
        - "mpi-m"
        - "nasa-giss"
        - "ncar"
        - "ncc"
        - "nerc"
        - "niwa"
        - "noaa-gfdl"
        - "ukmo"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: collaborative_institutions
    attributes:
      multiple: true
      label: Collaborative Institutions
      description: |
        Other institutions that collaborate on this model family.
        
        Leave empty if none.
      options:
        - "awi"
        - "bcc"
        - "cccma"
        - "cmcc"
        - "cnrm-cerfacs"
        - "csiro"
        - "csiro-arccss"
        - "dkrz"
        - "ec-earth-consortium"
        - "gfdl"
        - "inpe"
        - "ipsl"
        - "miroc"
        - "mohc"
        - "mpi-m"
        - "nasa-giss"
        - "ncar"
        - "ncc"
        - "nerc"
        - "niwa"
        - "noaa-gfdl"
        - "ukmo"

  - type: dropdown
    id: scientific_domains
    attributes:
      multiple: true
      label: Scientific Domains
      description: |
        The scientific domains covered by this family.
        
        <details markdown="1">
        <summary>Completion Guidance</summary>
        
        **Scientific domains** (from EMD component CV):
        
        Select all scientific domains covered by ANY member of this family.
        
        **Component types:**
        - **aerosol**: Behaviour and evolution of aerosols suspended in the atmosphere
        - **atmosphere**: Dynamical, thermodynamical, and physical processes in the atmosphere
        - **atmospheric-chemistry**: Behaviour and evolution of the chemical composition of the atmosphere
        - **land-ice**: Frozen freshwater in glaciers, ice-caps, ice-sheets, and ice-shelves
        - **land-surface**: Water, energy, and mass fluxes between the surface and the atmosphere
        - **ocean**: Dynamical, thermodynamical, and physical processes in the ocean
        - **ocean-biogeochemistry**: Biological, geological, and chemical processes in the ocean
        - **sea-ice**: Frozen seawater that floats on the ocean surface
        
        **Note:** Individual models in the family may cover a subset of these domains.
        
        </details>
      options:
        - "aerosol"
        - "atmosphere"
        - "atmospheric-chemistry"
        - "land-surface"
        - "land-ice"
        - "ocean"
        - "ocean-biogeochemistry"
        - "sea-ice"
    validations:
      required: true

  - type: input
    id: established
    attributes:
      label: Year Established
      description: |
        Year the model family was established.
        
        Leave blank if unknown.
      placeholder: "e.g., 2008"

  - type: input
    id: representative_member
    attributes:
      label: Representative Member
      description: |
        Name of a representative model from this family.
        
        <details markdown="1">
        <summary>Completion Guidance</summary>
        
        **Representative member:**
        
        A well-known or canonical member of the family.
        
        **Useful for:**
        - Quick reference to understand family characteristics
        - Finding documentation
        - Citation purposes
        
        **Can be:**
        - Most recent version
        - Most widely used version
        - Reference configuration
        
        **Leave blank if:**
        - First model in family
        - No clear representative yet
        
        </details>
      placeholder: "e.g., HadGEM3-GC31-LL"

  - type: input
    id: website
    attributes:
      label: Website URL
      description: |
        Official website for the model family.
        
        Leave blank if none.
        
        <details markdown="1">
        <summary>Completion Guidance</summary>
        
        **Official website:**
        
        URL with family documentation.
        
        **Ideal content:**
        - Model family overview
        - Technical documentation
        - Publication list
        - Code access information
        
        **Leave blank if:**
        - No dedicated website
        - Information scattered across papers
        
        </details>
      placeholder: "e.g., https://www.metoffice.gov.uk/research/approach/modelling-systems/unified-model"

  - type: textarea
    id: reference_dois
    attributes:
      label: Reference DOIs
      description: |
        Enter DOI URLs for key publications, one per line.
        
        Leave blank if none.
        
        <details markdown="1">
        <summary>Completion Guidance</summary>
        
        **Family-level publications:**
        
        Key publications about the model family as a whole.
        
        **Include:**
        - Family overview papers
        - Model genealogy studies (e.g., Masson and Knutti 2011)
        - Foundational technical papers
        
        **DO NOT include:**
        - Model-specific papers (those go in Model issues)
        - Component-specific papers (those go in Model Component issues)
        
        **Leave blank if:**
        - New family with no publications yet
        - Will add later
        
        </details>
      placeholder: "https://doi.org/10.1234/example1\nhttps://doi.org/10.1234/example2"

  - type: markdown
    attributes:
      value: |
        ## Issue Handling Metadata

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
