name: "Add/Modify: Model Component"
description: Register a model component (atmosphere, ocean, etc.) for EMD
title: "Add/Modify: Model Component: <Type component name here>"
labels: ['emd-submission', 'model-component', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Model Component Registration
        
        Register a dynamically simulated model component.
        
        Each component type (atmosphere, ocean, etc.) in a top-level model requires separate registration.
        
        See the [EMD Specification](https://wcrp-cmip.github.io/Essential-Model-Documentation/) for detailed guidance.

  - type: dropdown
    id: component
    attributes:
      label: Component Type
      description: |
        The type of model component.
        
        Must match one of the dynamic_components in the parent model.
      options:
        - "aerosol"
        - "atmosphere"
        - "atmospheric_chemistry"
        - "land_ice"
        - "land_surface"
        - "ocean"
        - "ocean_biogeochemistry"
        - "sea_ice"
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Component Name
      description: |
        The name of the model component.
        
        If embedded with no common name, use format: [HostName]-[component]
        
        Example: HadAM3-aerosol
      placeholder: "e.g., ARPEGE-Climat-v6.3, NEMO-v3.6, CLM5"
    validations:
      required: true

  - type: dropdown
    id: family
    attributes:
      label: Component Family
      description: |
        The component's family name (if applicable).
        
        Select 'None' if no family exists.
      options:
        - "Not applicable"
        - "ACCESS"
        - "BCC-CSM"
        - "BISICLES"
        - "CAM"
        - "CESM"
        - "CLM"
        - "CNRM-CM"
        - "CanESM"
        - "EC-Earth"
        - "FGOALS"
        - "GEOS"
        - "GFDL-CM4"
        - "GISS-E2"
        - "HadCM2"
        - "HadGEM3"
        - "ICON"
        - "IFS"
        - "IPSL-CM"
        - "MIROC"
        - "MPI-ESM"
        - "NICAM"
        - "UKESM1"

  - type: textarea
    id: description
    attributes:
      label: Scientific Description
      description: |
        Scientific overview of the component.
        
        Summarise the key processes simulated.
      placeholder: "Describe the key processes simulated by this component..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Component Relationships
        
        A component is either **embedded in** a host OR **coupled with** other components, never both.
        
        **Embedded**: Tightly integrated, shares host's grid, hard to extract
        **Coupled**: Recognizable name/version, exchanges through coupler, could transfer to another model

  - type: dropdown
    id: embedded_in
    attributes:
      label: Embedded In
      description: |
        If this component is embedded in a host component, select the host's component type.
        
        Leave as 'Not embedded' if not applicable.
      options:
        - "Not applicable"
        - "aerosol"
        - "atmosphere"
        - "atmospheric_chemistry"
        - "land_ice"
        - "land_surface"
        - "ocean"
        - "ocean_biogeochemistry"
        - "sea_ice"

  - type: dropdown
    id: coupled_with
    attributes:
      multiple: true
      label: Coupled With
      description: |
        Components this one is coupled with.
        
        **Only if NOT embedded.**
        
        Leave empty if embedded or not coupled.
      options:
        - "aerosol"
        - "atmosphere"
        - "atmospheric_chemistry"
        - "land_ice"
        - "land_surface"
        - "ocean"
        - "ocean_biogeochemistry"
        - "sea_ice"

  - type: markdown
    attributes:
      value: |
        ## Code and References

  - type: input
    id: code_base
    attributes:
      label: Code Base URL
      description: |
        URL to source code (preferably pointing to a specific version/commit).
        
        Enter 'private' if not publicly available.
        
        Leave blank if not available.
      placeholder: "e.g., https://github.com/org/repo/tree/v1.0 or private"

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Enter references in the format:
        
        citation: [Full citation text]
        doi: https://doi.org/[DOI]
        
        Separate multiple references with a blank line.
      placeholder: "citation: Smith, A. et al. (2024). Component description.\ndoi: https://doi.org/10.1234/example"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Computational Grids
        
        Reference existing grid definitions or leave blank to register new grids separately.
        
        Grid IDs follow format: c[NNN] for computational, v[NNN] for vertical

  - type: input
    id: horizontal_computational_grid
    attributes:
      label: Horizontal Computational Grid
      description: |
        ID of the horizontal computational grid (e.g., c100).
        
        Leave blank if component has no horizontal grid.
      placeholder: "e.g., c100"

  - type: input
    id: vertical_computational_grid
    attributes:
      label: Vertical Computational Grid
      description: |
        ID of the vertical computational grid (e.g., v100).
        
        Leave blank if component has no vertical grid.
      placeholder: "e.g., v100"

  - type: markdown
    attributes:
      value: |
        ## Issue Handling Metadata

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
