name: Model Family Registration
description: Register a model family for genealogy tracking
title: "[EMD] Model Family:"
labels: ['emd-submission', 'family', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Model Family Registration
        
        Registers a family of related models or components that share code.
        
        **Prerequisites:** None — submit before Stage 3 or 4 if needed.
        
        **Result:** Family ID (used in Stage 3 for Component Families, Stage 4 for Earth System Families)
        
        ![Workflow](https://mermaid.ink/svg/Zmxvd2NoYXJ0IExSCiAgICBzdWJncmFwaCBTdGFnZTFbIlN0YWdlIDEiXQogICAgICAgIFMxWyJHcmlkIENlbGxzICYgU3ViZ3JpZCJdCiAgICBlbmQKICAgIHN1YmdyYXBoIFN0YWdlMlsiU3RhZ2UgMiJdCiAgICAgICAgZGlyZWN0aW9uIFRCCiAgICAgICAgUzJhWyJIb3Jpem9udGFsIEdyaWQiXQogICAgICAgIFMyYlsiVmVydGljYWwgR3JpZCJdCiAgICBlbmQKICAgIHN1YmdyYXBoIE1GWyJNb2RlbCBGYW1pbHkiXQogICAgICAgIGRpcmVjdGlvbiBUQgogICAgICAgIEVTTVsiRWFydGggU3lzdGVtIEZhbWlseSJdCiAgICAgICAgQ0ZbIkNvbXBvbmVudCBGYW1pbHkiXQogICAgZW5kCiAgICBzdWJncmFwaCBTdGFnZTNbIlN0YWdlIDMiXQogICAgICAgIFMzWyJNb2RlbCBDb21wb25lbnQiXQogICAgZW5kCiAgICBzdWJncmFwaCBTdGFnZTRbIlN0YWdlIDQiXQogICAgICAgIFM0WyJNb2RlbCJdCiAgICBlbmQKICAgIFMxIC0tPnxnIyMjLCBzIyMjfCBTMmEKICAgIFMyYSAtLT58YyMjI3wgUzMKICAgIFMyYiAtLT58diMjI3wgUzMKICAgIFMzIC0tPnxjb25maWcgSUR8IFM0CiAgICBFU00gLS4tPnxmYW1pbHktaWR8IFM0CiAgICBDRiAtLi0-fGZhbWlseS1pZHwgUzMKICAgIHN0eWxlIFN0YWdlMSBzdHJva2U6IzMzMyxzdHJva2Utd2lkdGg6MnB4LGZpbGw6bm9uZQogICAgc3R5bGUgU3RhZ2UyIHN0cm9rZTojMzMzLHN0cm9rZS13aWR0aDoycHgsZmlsbDpub25lCiAgICBzdHlsZSBNRiBzdHJva2U6IzMzMyxzdHJva2Utd2lkdGg6MnB4LGZpbGw6bm9uZQogICAgc3R5bGUgU3RhZ2UzIHN0cm9rZTojMzMzLHN0cm9rZS13aWR0aDoycHgsZmlsbDpub25lCiAgICBzdHlsZSBTdGFnZTQgc3Ryb2tlOiMzMzMsc3Ryb2tlLXdpZHRoOjJweCxmaWxsOm5vbmUKICAgIHN0eWxlIE1GIHN0cm9rZTojMDA2NmNjLHN0cm9rZS13aWR0aDozcHgsZmlsbDpub25l)
        
        > ⚠️ **Read the guidance (▶) before filling in** — incorrect entries will be rejected. To modify an existing entry, check the [family files](https://github.com/WCRP-CMIP/Essential-Model-Documentation/tree/main/model_family).

  - type: input
    id: name
    attributes:
      label: Family Name
      description: |
        Short identifier for this model family.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Family identifier**
        
        Short name, often the first part of model names.
        
        **Examples:** HadGEM3, CESM, CNRM-CM, ACCESS, NEMO, CLM
        
        **Conventions:**
        - Use hyphens as separators
        - Typically: institution/project acronym + model type
        
        See [Masson and Knutti (2011)](https://doi.org/10.1029/2011GL046864) for model genealogy examples.
        
        </details>
      placeholder: "HadGEM3"
    validations:
      required: true

  - type: dropdown
    id: family_type
    attributes:
      label: Family Type
      description: |
        Whether this is a coupled Earth System family or single-domain Component family.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Family classification**
        
        Determines how this family is used in the workflow.
        
        **Earth System Model:**
        - Coupled models with multiple interacting components
        - Include atmosphere AND ocean/land-surface
        - Examples: CESM, HadGEM3, CNRM-CM, ACCESS, IPSL-CM
        - Referenced in Stage 4 (Model)
        
        **Component Family:**
        - Single scientific domain
        - May be coupled into larger systems
        - Examples: NEMO (ocean), CAM (atmosphere), CLM (land)
        - Referenced in Stage 3 (Model Component)
        
        </details>
      options:
        - "Not specified"
        - "Earth System Model"
        - "Component Family"
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        What characterizes this model family.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Family characterization**
        
        **What to include:**
        1. Scientific focus and approach
        2. Common code base and physics
        3. How family members differ (resolution, components, parameters)
        
        2-3 paragraphs typical.
        
        </details>
      placeholder: "1. Scientific focus and approach
2. Common code base and physics
3. How family members differ"
    validations:
      required: true

  - type: dropdown
    id: primary_institution
    attributes:
      label: Primary Institution
      description: |
        Lead institution responsible for development.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Lead institution**
        
        Institution primarily responsible for development and maintenance.
        
        </details>
      options:
        - "Not specified"
        - "awi"
        - "bas"
        - "bcc"
        - "bom"
        - "cas"
        - "cccma"
        - "cmcc"
        - "cnrm"
        - "cnrm-cerfacs"
        - "csiro"
        - "dkrz"
        - "dwd"
        - "ec-earth-consortium"
        - "ecmwf"
        - "ipsl"
        - "jamstec"
        - "lbnl"
        - "miroc"
        - "mohc"
        - "mpi-m"
        - "nasa-giss"
        - "nasa-gsfc"
        - "ncar"
        - "ncas"
        - "nerc"
        - "noaa-gfdl"
        - "noc"
        - "pnnl"
        - "uob"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: collaborative_institutions
    attributes:
      multiple: true
      label: Collaborative Institutions
      description: |
        Other institutions contributing to development.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Contributing institutions**
        
        Other institutions involved in development.
        
        **Leave empty if:** Single-institution project.
        
        </details>
      options:
        - "awi"
        - "bas"
        - "bcc"
        - "bom"
        - "cas"
        - "cccma"
        - "cmcc"
        - "cnrm"
        - "cnrm-cerfacs"
        - "csiro"
        - "dkrz"
        - "dwd"
        - "ec-earth-consortium"
        - "ecmwf"
        - "ipsl"
        - "jamstec"
        - "lbnl"
        - "miroc"
        - "mohc"
        - "mpi-m"
        - "nasa-giss"
        - "nasa-gsfc"
        - "ncar"
        - "ncas"
        - "nerc"
        - "noaa-gfdl"
        - "noc"
        - "pnnl"
        - "uob"

  - type: dropdown
    id: scientific_domains
    attributes:
      multiple: true
      label: Scientific Domains
      description: |
        All domains covered by any family member.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Domains covered**
        
        All domains covered by ANY member of this family.
        
        - aerosol, atmosphere, atmospheric-chemistry
        - land-ice, land-surface
        - ocean, ocean-biogeochemistry, sea-ice
        
        Individual models may cover a subset.
        
        </details>
      options:
        - "aerosol"
        - "atmosphere"
        - "atmospheric-chemistry"
        - "land-ice"
        - "land-surface"
        - "ocean"
        - "ocean-biogeochemistry"
        - "sea-ice"
    validations:
      required: true

  - type: input
    id: established
    attributes:
      label: Year Established
      description: |
        Year the family was first developed.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Year established**
        
        When the family was first developed.
        
        **Leave blank if:** Unknown.
        
        </details>
      placeholder: "2009"

  - type: input
    id: representative_member
    attributes:
      label: Representative Member
      description: |
        A well-known configuration from this family.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Canonical configuration**
        
        A well-known member for quick reference.
        
        **Examples:** HadGEM3-GC31-LL, CESM2, CNRM-CM6-1
        
        </details>
      placeholder: "HadGEM3-GC31-LL"

  - type: input
    id: website
    attributes:
      label: Website
      description: |
        Official documentation URL.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Documentation URL**
        
        Official website with family documentation, technical references, or code access.
        
        </details>
      placeholder: "https://www.metoffice.gov.uk/research/approach/modelling-systems/unified-model"

  - type: textarea
    id: reference_dois
    attributes:
      label: Reference DOIs
      description: |
        DOI URLs for family-level publications.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Family-level publications**
        
        DOIs for papers describing the family as a whole.
        
        **Format:** `https://doi.org/...` (one per line)
        
        **Do NOT include:** Model-specific or component-specific papers.
        
        </details>
      placeholder: "https://doi.org/10.1029/2019MS001995"

  - type: markdown
    attributes:
      value: |
        ---
        
        ## Issue Handling
        
        **After submission:**
        - Creates `model_family` entry
        - Earth System Families can be referenced in Stage 4 (Model)
        - Component Families can be referenced in Stage 3 (Model Component)
        - Track progress in issue comments

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: New submission or modification.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
