name: "Add/Modify: Model Family"
description: Register a model family (group of related models)
title: "Add/Modify: Model Family: <Type family name here>"
labels: ['emd-submission', 'model-family', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Model Family Registration
        
        Register a model family - a group of models sharing code bases.
        
        Model families help establish model genealogies for inter-model comparisons.
        
        See [Masson and Knutti (2011)](https://doi.org/10.1029/2011GL046864) for examples.

  - type: input
    id: name
    attributes:
      label: Family Name
      description: |
        The family name.
        
        Often persists across model versions and may be the first part of full model names.
      placeholder: "e.g., HadGEM3, CESM, CNRM-CM, ACCESS"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Description of the model family.
        
        Include scientific focus and common characteristics shared by family members.
      placeholder: "Describe the model family, its scientific focus, and common characteristics..."
    validations:
      required: true

  - type: dropdown
    id: primary_institution
    attributes:
      label: Primary Institution
      description: The primary institution responsible for the model family.
      options:
        - "ACCESS-NRI"
        - "ACMAD"
        - "AEMET"
        - "AER"
        - "AMAP"
        - "ANL"
        - "ANU"
        - "AORI"
        - "APCC"
        - "ARCCSS"
        - "AS-RCEC"
        - "ASMERC"
        - "AUoT"
        - "AWI"
        - "AoR"
        - "BAS"
        - "BCC"
        - "BCCR"
        - "BIRA-IASB"
        - "BNL"
        - "BNU"
        - "BOEM"
        - "BOKU"
        - "BlackRock"
        - "C-DAC"
        - "CAMS"
        - "CAS"
        - "CCCR-IITM"
        - "CCCma"
        - "CCRS"
        - "CEDA"
        - "CEMA"
        - "CEMC"
        - "CEMIG"
        - "CENICAFÉ"
        - "CERFACS"
        - "CESDAC"
        - "CETESB"
        - "CGI"
        - "CGISC"
        - "CIAT"
        - "CICERO"
        - "CICESE"
        - "CIMA"
        - "CLEX"
        - "CMA"
        - "CMCC"
        - "CMIP-IPO"
        - "CNES"
        - "CNR"
        - "CNRM"
        - "CNRM-CERFACS"
        - "CNRS"
        - "COLA"
        - "COMSATS"
        - "CR"
        - "CREAF"
        - "CSC"
        - "CSIC"
        - "CSIR"
        - "CSIR-Wits-CSIRO"
        - "CSIRO"
        - "CU"
        - "CUG"
        - "Caltech"
        - "Cineca"
        - "DESNZ"
        - "DIAS"
        - "DKRZ"
        - "DLR"
        - "DMI"
        - "DSIT"
        - "DTU"
        - "DWD"
        - "E3SM-Project"
        - "EAWAG"
        - "EC-Earth-Consortium"
        - "ECCC"
        - "ECMWF"
        - "EDF"
        - "ENS"
        - "ENVEO"
        - "ESA"
        - "ESCWA"
        - "ESSO"
        - "ESSTI"
        - "ETH-Zürich"
        - "Empa"
        - "FACET"
        - "FAO"
        - "FIO"
        - "FIO-QLNM"
        - "FMI"
        - "FSU"
        - "FUB"
        - "FUBerlin"
        - "FZJ"
        - "Fidelidade"
        - "GCISC"
        - "GERICS"
        - "GMU"
        - "GTI"
        - "HEREON"
        - "HKUST"
        - "HUJI"
        - "IAA"
        - "IACETH"
        - "IAP"
        - "ICAR"
        - "ICHEC"
        - "ICTP"
        - "IDRC"
        - "IEK"
        - "IFCA"
        - "IFM-GEOMAR"
        - "IFREMER"
        - "IGCI"
        - "IIASA"
        - "IIHS"
        - "IIS"
        - "IISER"
        - "IIT"
        - "IITM"
        - "INGV"
        - "INM"
        - "INMET"
        - "INPA"
        - "INPE"
        - "INRAE"
        - "IOW"
        - "IPCC"
        - "IPSL"
        - "IRD"
        - "ISDR"
        - "ISM"
        - "ISSI"
        - "IST"
        - "ISU"
        - "ITM"
        - "ImperialCollege"
        - "JAMSTEC"
        - "JAXA"
        - "JCU"
        - "JGCRI"
        - "KAIST"
        - "KAUST"
        - "KCL"
        - "KIOST"
        - "KIT"
        - "KMA"
        - "KNMI"
        - "KSU"
        - "LANL"
        - "LBNL"
        - "LLNL"
        - "LMD"
        - "LMU"
        - "LPC2E"
        - "LSCE"
        - "LSE"
        - "LSHTM"
        - "LSU"
        - "LiU"
        - "MARN"
        - "MEXT"
        - "MIROC"
        - "MIT"
        - "MOHC"
        - "MPI-B"
        - "MPI-BGC"
        - "MPI-C"
        - "MPI-G"
        - "MPI-M"
        - "MPS"
        - "MRI"
        - "MTU"
        - "Météo-France"
        - "NASA"
        - "NASA-GISS"
        - "NASA-GSFC"
        - "NASA-JPL"
        - "NASA-LaRC"
        - "NAU"
        - "NCAR"
        - "NCAS"
        - "NCC"
        - "NCEO"
        - "NCEP"
        - "NCI"
        - "NCM"
        - "NCState"
        - "NERC"
        - "NERSC"
        - "NIES"
        - "NILU"
        - "NIMR"
        - "NIMS"
        - "NIMS-KMA"
        - "NIWA"
        - "NLR"
        - "NOA"
        - "NOAA"
        - "NOAA-GFDL"
        - "NOAA-NCEI"
        - "NOC"
        - "NORCE"
        - "NRL"
        - "NSF"
        - "NTNU"
        - "NTU"
        - "NUI"
        - "NUIST"
        - "NYU"
        - "OGS"
        - "OJERI"
        - "ORNL"
        - "OSU"
        - "Ouranos"
        - "PAUWES"
        - "PBL"
        - "PCMDI"
        - "PIK"
        - "PMAS-AAUR"
        - "PML"
        - "PMOD"
        - "PNNL"
        - "PNNL-JGCRI"
        - "PNNL-WACCEM"
        - "PNU"
        - "QCCCE"
        - "QLNM"
        - "R-CCS"
        - "RAL"
        - "RCEC"
        - "RSS"
        - "RU-CORE"
        - "RWE"
        - "SAL"
        - "SJSU"
        - "SKYE"
        - "SMHI"
        - "SMU"
        - "SNU"
        - "SOLARIS HEPPA"
        - "STFC"
        - "SWP"
        - "TAMU"
        - "TERI"
        - "THU"
        - "TMA"
        - "TROPOS"
        - "TUBITAK"
        - "TUDelft"
        - "TUM"
        - "TUW"
        - "TWP"
        - "TenneT"
        - "UA"
        - "UAAR"
        - "UAH"
        - "UAL"
        - "UBA"
        - "UBC"
        - "UCAD"
        - "UCAR"
        - "UCBerkeley"
        - "UCI"
        - "UCL"
        - "UCLA"
        - "UCLouvain"
        - "UCM"
        - "UCRiverside"
        - "UCSB"
        - "UCSC"
        - "UCSD"
        - "UCT"
        - "UColorado"
        - "UEA"
        - "UERJ"
        - "UFRN"
        - "UFZ"
        - "UGA"
        - "UHH"
        - "UIUC"
        - "UKCEH"
        - "ULB"
        - "UMN"
        - "UNIPAMPA"
        - "UNIST"
        - "UNSTIM"
        - "UNSW"
        - "UReading"
        - "USD"
        - "USGS"
        - "UTAS"
        - "UTAustin"
        - "UU"
        - "UW"
        - "UiB"
        - "UiO"
        - "UoBergen"
        - "UoH"
        - "UoLeeds"
        - "UoM"
        - "UoMontreal"
        - "UoOtago"
        - "UoOulu"
        - "UoSask"
        - "UofMD"
        - "UofT"
        - "VUA"
        - "WCRC"
        - "WCRP"
        - "WMO"
        - "WSL"
        - "WUR"
        - "WWRP"
        - "Wits"
        - "uOttawa"
    validations:
      required: true

  - type: dropdown
    id: collaborative_institutions
    attributes:
      multiple: true
      label: Collaborative Institutions
      description: |
        Other institutions that collaborate on this model family.
        
        Leave empty if none.
      options:
        - "ACCESS-NRI"
        - "ACMAD"
        - "AEMET"
        - "AER"
        - "AMAP"
        - "ANL"
        - "ANU"
        - "AORI"
        - "APCC"
        - "ARCCSS"
        - "AS-RCEC"
        - "ASMERC"
        - "AUoT"
        - "AWI"
        - "AoR"
        - "BAS"
        - "BCC"
        - "BCCR"
        - "BIRA-IASB"
        - "BNL"
        - "BNU"
        - "BOEM"
        - "BOKU"
        - "BlackRock"
        - "C-DAC"
        - "CAMS"
        - "CAS"
        - "CCCR-IITM"
        - "CCCma"
        - "CCRS"
        - "CEDA"
        - "CEMA"
        - "CEMC"
        - "CEMIG"
        - "CENICAFÉ"
        - "CERFACS"
        - "CESDAC"
        - "CETESB"
        - "CGI"
        - "CGISC"
        - "CIAT"
        - "CICERO"
        - "CICESE"
        - "CIMA"
        - "CLEX"
        - "CMA"
        - "CMCC"
        - "CMIP-IPO"
        - "CNES"
        - "CNR"
        - "CNRM"
        - "CNRM-CERFACS"
        - "CNRS"
        - "COLA"
        - "COMSATS"
        - "CR"
        - "CREAF"
        - "CSC"
        - "CSIC"
        - "CSIR"
        - "CSIR-Wits-CSIRO"
        - "CSIRO"
        - "CU"
        - "CUG"
        - "Caltech"
        - "Cineca"
        - "DESNZ"
        - "DIAS"
        - "DKRZ"
        - "DLR"
        - "DMI"
        - "DSIT"
        - "DTU"
        - "DWD"
        - "E3SM-Project"
        - "EAWAG"
        - "EC-Earth-Consortium"
        - "ECCC"
        - "ECMWF"
        - "EDF"
        - "ENS"
        - "ENVEO"
        - "ESA"
        - "ESCWA"
        - "ESSO"
        - "ESSTI"
        - "ETH-Zürich"
        - "Empa"
        - "FACET"
        - "FAO"
        - "FIO"
        - "FIO-QLNM"
        - "FMI"
        - "FSU"
        - "FUB"
        - "FUBerlin"
        - "FZJ"
        - "Fidelidade"
        - "GCISC"
        - "GERICS"
        - "GMU"
        - "GTI"
        - "HEREON"
        - "HKUST"
        - "HUJI"
        - "IAA"
        - "IACETH"
        - "IAP"
        - "ICAR"
        - "ICHEC"
        - "ICTP"
        - "IDRC"
        - "IEK"
        - "IFCA"
        - "IFM-GEOMAR"
        - "IFREMER"
        - "IGCI"
        - "IIASA"
        - "IIHS"
        - "IIS"
        - "IISER"
        - "IIT"
        - "IITM"
        - "INGV"
        - "INM"
        - "INMET"
        - "INPA"
        - "INPE"
        - "INRAE"
        - "IOW"
        - "IPCC"
        - "IPSL"
        - "IRD"
        - "ISDR"
        - "ISM"
        - "ISSI"
        - "IST"
        - "ISU"
        - "ITM"
        - "ImperialCollege"
        - "JAMSTEC"
        - "JAXA"
        - "JCU"
        - "JGCRI"
        - "KAIST"
        - "KAUST"
        - "KCL"
        - "KIOST"
        - "KIT"
        - "KMA"
        - "KNMI"
        - "KSU"
        - "LANL"
        - "LBNL"
        - "LLNL"
        - "LMD"
        - "LMU"
        - "LPC2E"
        - "LSCE"
        - "LSE"
        - "LSHTM"
        - "LSU"
        - "LiU"
        - "MARN"
        - "MEXT"
        - "MIROC"
        - "MIT"
        - "MOHC"
        - "MPI-B"
        - "MPI-BGC"
        - "MPI-C"
        - "MPI-G"
        - "MPI-M"
        - "MPS"
        - "MRI"
        - "MTU"
        - "Météo-France"
        - "NASA"
        - "NASA-GISS"
        - "NASA-GSFC"
        - "NASA-JPL"
        - "NASA-LaRC"
        - "NAU"
        - "NCAR"
        - "NCAS"
        - "NCC"
        - "NCEO"
        - "NCEP"
        - "NCI"
        - "NCM"
        - "NCState"
        - "NERC"
        - "NERSC"
        - "NIES"
        - "NILU"
        - "NIMR"
        - "NIMS"
        - "NIMS-KMA"
        - "NIWA"
        - "NLR"
        - "NOA"
        - "NOAA"
        - "NOAA-GFDL"
        - "NOAA-NCEI"
        - "NOC"
        - "NORCE"
        - "NRL"
        - "NSF"
        - "NTNU"
        - "NTU"
        - "NUI"
        - "NUIST"
        - "NYU"
        - "OGS"
        - "OJERI"
        - "ORNL"
        - "OSU"
        - "Ouranos"
        - "PAUWES"
        - "PBL"
        - "PCMDI"
        - "PIK"
        - "PMAS-AAUR"
        - "PML"
        - "PMOD"
        - "PNNL"
        - "PNNL-JGCRI"
        - "PNNL-WACCEM"
        - "PNU"
        - "QCCCE"
        - "QLNM"
        - "R-CCS"
        - "RAL"
        - "RCEC"
        - "RSS"
        - "RU-CORE"
        - "RWE"
        - "SAL"
        - "SJSU"
        - "SKYE"
        - "SMHI"
        - "SMU"
        - "SNU"
        - "SOLARIS HEPPA"
        - "STFC"
        - "SWP"
        - "TAMU"
        - "TERI"
        - "THU"
        - "TMA"
        - "TROPOS"
        - "TUBITAK"
        - "TUDelft"
        - "TUM"
        - "TUW"
        - "TWP"
        - "TenneT"
        - "UA"
        - "UAAR"
        - "UAH"
        - "UAL"
        - "UBA"
        - "UBC"
        - "UCAD"
        - "UCAR"
        - "UCBerkeley"
        - "UCI"
        - "UCL"
        - "UCLA"
        - "UCLouvain"
        - "UCM"
        - "UCRiverside"
        - "UCSB"
        - "UCSC"
        - "UCSD"
        - "UCT"
        - "UColorado"
        - "UEA"
        - "UERJ"
        - "UFRN"
        - "UFZ"
        - "UGA"
        - "UHH"
        - "UIUC"
        - "UKCEH"
        - "ULB"
        - "UMN"
        - "UNIPAMPA"
        - "UNIST"
        - "UNSTIM"
        - "UNSW"
        - "UReading"
        - "USD"
        - "USGS"
        - "UTAS"
        - "UTAustin"
        - "UU"
        - "UW"
        - "UiB"
        - "UiO"
        - "UoBergen"
        - "UoH"
        - "UoLeeds"
        - "UoM"
        - "UoMontreal"
        - "UoOtago"
        - "UoOulu"
        - "UoSask"
        - "UofMD"
        - "UofT"
        - "VUA"
        - "WCRC"
        - "WCRP"
        - "WMO"
        - "WSL"
        - "WUR"
        - "WWRP"
        - "Wits"
        - "uOttawa"

  - type: dropdown
    id: scientific_domains
    attributes:
      multiple: true
      label: Scientific Domains
      description: The scientific domains covered by this family.
      options:
        - "aerosol"
        - "atmosphere"
        - "atmospheric_chemistry"
        - "land_ice"
        - "land_surface"
        - "ocean"
        - "ocean_biogeochemistry"
        - "sea_ice"
    validations:
      required: true

  - type: input
    id: established
    attributes:
      label: Year Established
      description: |
        Year the model family was established.
        
        Leave blank if unknown.
      placeholder: "e.g., 2008"

  - type: input
    id: representative_member
    attributes:
      label: Representative Member
      description: Name of a representative model from this family.
      placeholder: "e.g., HadGEM3-GC31-LL"

  - type: input
    id: website
    attributes:
      label: Website URL
      description: |
        Official website for the model family.
        
        Leave blank if none.
      placeholder: "e.g., https://www.metoffice.gov.uk/research/approach/modelling-systems/unified-model"

  - type: textarea
    id: reference_dois
    attributes:
      label: Reference DOIs
      description: |
        Enter DOI URLs for key publications, one per line.
        
        Leave blank if none.
      placeholder: "https://doi.org/10.1234/example1\nhttps://doi.org/10.1234/example2"

  - type: markdown
    attributes:
      value: |
        ## Issue Handling Metadata

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
