name: Model Component Submission
description: Submit metadata for a model component as specified in the EMD specification.
title: "[EMD] Model Component Submission"
labels: ['emd-submission', 'component']
body:
  - type: markdown
    attributes:
      value: |
        # Model Component Documentation
        
        This template documents individual components of your climate model as required for CMIP7 participation. Each component description enables traceability across different models, supports scientific evaluation, and is mandatory for publishing model data to ESGF. The information you provide helps the climate modeling community understand your component's scientific basis, track how components are shared between institutions, and ensure proper attribution in research studies.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: |
        Select the process that this model component simulates.
        
        MANDATORY field from Model component process CV.
      options:
        - "aerosol"
        - "atmos"
        - "atmosChem"
        - "land"
        - "landIce"
        - "ocean"
        - "ocnBgchem"
        - "seaIce"
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Name
      description: |
        The name of the model component.
        
        MANDATORY field.
      placeholder: "e.g., ECHAM6.3, NEMO3.6"
    validations:
      required: true

  - type: input
    id: family
    attributes:
      label: Family
      description: |
        The name of the family of models that the model component belongs to.
        
        MANDATORY field.
      placeholder: "e.g., ECHAM, NEMO, CLM"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A scientific overview of the model component.
        
        MANDATORY field.
      placeholder: "Provide a scientific overview summarizing key processes simulated, scientific basis, and MIP-relevant details."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## References
        
        MANDATORY: Each reference must include both Citation and DOI properties.

  - type: textarea
    id: reference_1_citation
    attributes:
      label: Reference 1 - Citation
      description: |
        Human-readable citation for the primary component reference.
        
        MANDATORY field.
      placeholder: "Author(s). (Year). Title. Journal/Report."
    validations:
      required: true

  - type: input
    id: reference_1_doi
    attributes:
      label: Reference 1 - DOI
      description: |
        The persistent identifier (DOI) for the primary component reference.
        
        MANDATORY field.
      placeholder: "https://doi.org/..."
    validations:
      required: true

  - type: input
    id: code_base
    attributes:
      label: Code Base
      description: |
        A URL (preferably DOI) for the source code.
        
        MANDATORY field. Set to 'private' if not publicly available.
      placeholder: "https://github.com/org/repo/tree/v1.2.3 or 'private'"
    validations:
      required: true

  - type: dropdown
    attributes:
      multiple: true
      label: Embedded In
      description: |
        Select the model component(s) in which this component is embedded.
        
        Select all that apply.
        
        OPTIONAL field from Model component process CV.
      options:
        - "aerosol"
        - "atmos"
        - "atmosChem"
        - "land"
        - "landIce"
        - "ocean"
        - "ocnBgchem"
        - "seaIce"

  - type: dropdown
    attributes:
      multiple: true
      label: Coupled With
      description: |
        Select the model component(s) to which this component is coupled.
        
        Select all that apply.
        
        OPTIONAL field from Model component process CV.
      options:
        - "aerosol"
        - "atmos"
        - "atmosChem"
        - "land"
        - "landIce"
        - "ocean"
        - "ocnBgchem"
        - "seaIce"

  - type: markdown
    attributes:
      value: |
        ## Native Horizontal Grid
        
        MANDATORY compound object describing the component's horizontal grid.

  - type: dropdown
    id: horizontal_grid
    attributes:
      label: Grid
      description: |
        The horizontal grid type.
        
        MANDATORY field from Native horizontal grid Type CV.
      options:
        - "no-horizontal-grid"
        - "cubed-sphere"
        - "cubic-octahedral-spectral-reduced-gaussian"
        - "displaced-pole"
        - "icosahedral-geodesic-dual"
        - "icosahedral-geodesic"
        - "linear-spectral-gaussian"
        - "no-grid"
        - "plane-projection"
        - "quadratic-spectral-gaussian"
        - "reduced-gaussian"
        - "regular-gaussian"
        - "regular-latitude-longitude"
        - "rotated-pole"
        - "spectral-gaussian"
        - "spectral-reduced-gaussian"
        - "stretched"
        - "tripolar"
        - "unstructured-polygonal"
        - "unstructured-triangular"
        - "yin-yang"
    validations:
      required: true

  - type: textarea
    id: horizontal_description
    attributes:
      label: Description (Optional)
      description: |
        Free-text description of the horizontal grid.
        
        OPTIONAL field.
      placeholder: "Additional horizontal grid details if needed"

  - type: dropdown
    id: horizontal_grid_mapping
    attributes:
      label: Grid Mapping
      description: |
        The coordinate reference system of the horizontal coordinates.
        
        MANDATORY field from Grid Mapping CV.
      options:
        - "albers_conical_equal_area"
        - "azimuthal_equidistant"
        - "geostationary"
        - "lambert_azimuthal_equal_area"
        - "lambert_conformal_conic"
        - "lambert_cylindrical_equal_area"
        - "latitude_longitude"
        - "orthographic"
        - "polar_stereographic"
        - "rotated_latitude_longitude"
        - "sinusoidal"
        - "stereographic"
        - "transverse_mercator"
        - "vertical_perspective"
    validations:
      required: true

  - type: dropdown
    id: horizontal_region
    attributes:
      label: Region
      description: |
        The portion of the globe where horizontal grid calculations are performed.
        
        MANDATORY field from Region CV.
      options:
        - "antarctica"
        - "global"
        - "greenland"
        - "limited-area"
    validations:
      required: true

  - type: dropdown
    id: horizontal_temporal_refinement
    attributes:
      label: Temporal Refinement
      description: |
        How the distribution of grid cells varies with time.
        
        MANDATORY field from Temporal refinement CV.
      options:
        - "adaptive"
        - "dynamically-stretched"
        - "static"
    validations:
      required: true

  - type: dropdown
    id: horizontal_arrangement
    attributes:
      label: Arrangement
      description: |
        Grid arrangement of orthogonal physical quantities.
        
        MANDATORY field from Arrangement CV.
      options:
        - "arakawa_A"
        - "arakawa_B"
        - "arakawa_C"
        - "arakawa_D"
        - "arakawa_E"
    validations:
      required: true

  - type: input
    id: horizontal_resolution_x
    attributes:
      label: Resolution X
      description: |
        Horizontal resolution in X direction (float).
        
        OPTIONAL field.
      placeholder: "e.g., 1.25"

  - type: input
    id: horizontal_resolution_y
    attributes:
      label: Resolution Y
      description: |
        Horizontal resolution in Y direction (float).
        
        OPTIONAL field.
      placeholder: "e.g., 0.9375"

  - type: dropdown
    id: horizontal_units
    attributes:
      label: Horizontal Units
      description: |
        Units for resolution_x and resolution_y.
        
        OPTIONAL field - Required if resolution_x or resolution_y are set.
      options:
        - "degrees"
        - "km"
        - "m"

  - type: input
    id: horizontal_n_cells
    attributes:
      label: N Cells
      description: |
        Total number of grid cells.
        
        MANDATORY integer field.
      placeholder: "e.g., 139968"
    validations:
      required: true

  - type: input
    id: horizontal_n_sides
    attributes:
      label: N Sides
      description: |
        Number of cell sides (edges) for unstructured grids.
        
        OPTIONAL integer field.
      placeholder: "e.g., 714274"

  - type: input
    id: horizontal_n_vertices
    attributes:
      label: N Vertices
      description: |
        Number of vertices (nodes) for unstructured grids.
        
        OPTIONAL integer field.
      placeholder: "e.g., 567145"

  - type: dropdown
    id: horizontal_truncation_method
    attributes:
      label: Truncation Method
      description: |
        Method for truncating spherical harmonic expansion.
        
        OPTIONAL field from Truncation method CV.
      options:
        - "triangular"
        - "rhomboidal"

  - type: input
    id: horizontal_truncation_number
    attributes:
      label: Truncation Number
      description: |
        Truncation number for spectral grids.
        
        OPTIONAL integer field.
      placeholder: "e.g., 63"

  - type: input
    id: horizontal_resolution_range_km
    attributes:
      label: Resolution Range (km)
      description: |
        Minimum and maximum resolution in km.
        
        MANDATORY field as [float,float].
        
        Format: min, max
      placeholder: "e.g., 57.0, 290"
    validations:
      required: true

  - type: input
    id: horizontal_mean_resolution_km
    attributes:
      label: Mean Resolution (km)
      description: |
        Mean resolution in km.
        
        MANDATORY float field.
      placeholder: "e.g., 234.5"
    validations:
      required: true

  - type: dropdown
    id: horizontal_nominal_resolution
    attributes:
      label: Nominal Resolution
      description: |
        Nominal resolution characterizing the grid.
        
        MANDATORY field from Nominal resolution CV.
      options:
        - "0.5 km"
        - "10000 km"
        - "1000 km"
        - "100 km"
        - "10 km"
        - "1 km"
        - "1x1 degree"
        - "2.5 km"
        - "2500 km"
        - "250 km"
        - "25 km"
        - "5000 km"
        - "500 km"
        - "50 km"
        - "5 km"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Native Vertical Grid
        
        MANDATORY compound object describing the component's vertical grid.

  - type: dropdown
    id: vertical_coordinate
    attributes:
      label: Coordinate
      description: |
        The coordinate type of the vertical grid.
        
        MANDATORY field from Coordinate CV.
      options:
        - "no-vertical-grid"
        - "air-potential-temperature"
        - "air-pressure"
        - "atmosphere-hybrid-height-coordinate"
        - "atmosphere-hybrid-sigma-pressure-coordinate"
        - "atmosphere-ln-pressure-coordinate"
        - "atmosphere-sigma-coordinate"
        - "atmosphere-sleve-coordinate"
        - "depth"
        - "geopotential-height"
        - "height"
        - "ocean-double-sigma-coordinate"
        - "ocean-s-coordinate-g1"
        - "ocean-s-coordinate-g2"
        - "ocean-s-coordinate"
        - "ocean-sigma-coordinate"
        - "ocean-sigma-z-coordinate"
        - "sea-water-potential-temperature"
        - "sea-water-pressure"
    validations:
      required: true

  - type: textarea
    id: vertical_description
    attributes:
      label: Description (Optional)
      description: |
        Free-text description of the vertical grid.
        
        OPTIONAL field.
      placeholder: "Additional vertical grid details if needed"

  - type: input
    id: vertical_n_z
    attributes:
      label: N z
      description: |
        Number of grid cells in Z direction.
        
        OPTIONAL integer field. Must be omitted if n_z_range is set.
      placeholder: "e.g., 70"

  - type: input
    id: vertical_n_z_range
    attributes:
      label: N z Range
      description: |
        Minimum and maximum number of Z grid cells for variable resolution.
        
        OPTIONAL field as [integer,integer]. Must be omitted if n_z is set.
        
        Format: min, max
      placeholder: "e.g., 5, 15"

  - type: input
    id: vertical_bottom_layer_thickness
    attributes:
      label: Bottom Layer Thickness
      description: |
        Thickness of bottom model layer.
        
        OPTIONAL float field.
      placeholder: "e.g., 10.0"

  - type: input
    id: vertical_top_layer_thickness
    attributes:
      label: Top Layer Thickness
      description: |
        Thickness of top model layer.
        
        OPTIONAL float field.
      placeholder: "e.g., 10.0"

  - type: input
    id: vertical_top_of_model
    attributes:
      label: Top of Model
      description: |
        Value of upper boundary of top model layer.
        
        OPTIONAL float field.
      placeholder: "e.g., 85003.5"

  - type: dropdown
    id: vertical_units
    attributes:
      label: Vertical Units
      description: |
        Physical units for thickness and boundary values.
        
        OPTIONAL field - Required if any thickness/boundary values are set.
      options:
        - "K"
        - "m"
        - "Pa"

  - type: dropdown
    id: issue_category
    attributes:
      label: Issue Type
      description: This is pre-set and cannot be changed.
      options:
        - "component"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "new"
        - "modify"
      default: 0
    validations:
      required: true
