name: "Stage 2b: Vertical Computational Grid"
description: Register vertical computational grid (Stage 2b of 4)
title: "[EMD] Vertical Grid:"
labels: ['emd-submission', 'grid', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Stage 2b: Vertical Computational Grid
        
        Defines the vertical level structure for a model component.
        
        **Prerequisites:** None — can be submitted in parallel with Stage 2a.
        
        ```mermaid
        flowchart LR
            subgraph Stage1[\**Stage 1**\"]
                S1[\"Grid Cells & Subgrid\"]
            end
            subgraph Stage2[\"**Stage 2**\"]
                direction TB
                S2a[\"Horizontal Grid\"]
                S2b[\"Vertical Grid\"]
            end
            subgraph MF[\"**Model Family**\"]
                direction TB
                ESM[\"Earth System Family\"]
                CF[\"Component Family\"]
            end
            subgraph Stage3[\"**Stage 3**\"]
                S3[\"Model Component\"]
            end
            subgraph Stage4[\"**Stage 4**\"]
                S4[\"Model\"]
            end
            S1 -->|g###
       ```

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Brief characterization of this vertical grid.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Grid characterization**
        
        Brief description of this vertical grid.
        
        **What to include:**
        1. Number of levels
        2. Coordinate type
        3. Vertical extent
        
        **Examples:**
        - '91-level hybrid sigma-pressure coordinate extending to 0.01 hPa'
        - '75-level z-coordinate ocean grid from surface to 6000m'
        - '14 soil layers from 0.01m to 12m depth'
        
        </details>
      placeholder: "1. Number of levels\n2. Coordinate type\n3. Vertical extent"
    validations:
      required: true

  - type: dropdown
    id: vertical_coordinate
    attributes:
      label: Coordinate Type
      description: |
        Vertical coordinate system.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Coordinate system**
        
        **Atmosphere:**
        - **atmosphere-hybrid-height-coordinate**: Height-based with terrain following near surface
        - **atmosphere-hybrid-sigma-pressure-coordinate**: Pressure-based with terrain following (most common)
        - **atmosphere-sigma-coordinate**: Pure terrain-following
        
        **Ocean:**
        - **depth**: Fixed depth levels (z-coordinate)
        - **ocean-s-coordinate**: Stretched terrain-following
        - **ocean-sigma-coordinate**: Pure terrain-following
        - **ocean-sigma-z-coordinate**: Hybrid sigma near coast, z in deep ocean
        
        **Other:**
        - **height**: Simple height coordinate (ice, snow)
        - **land-ice-sigma-coordinate**: Ice sheet terrain-following
        
        See [CF Conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#dimensionless-v-coord) for details.
        
        </details>
      options:
        - "Not specified"
        - "atmosphere-hybrid-height-coordinate"
        - "atmosphere-hybrid-sigma-pressure-coordinate"
        - "atmosphere-sigma-coordinate"
        - "depth"
        - "height"
        - "ocean-s-coordinate"
        - "ocean-sigma-coordinate"
        - "ocean-sigma-z-coordinate"
        - "land-ice-sigma-coordinate"
      default: 0
    validations:
      required: true

  - type: input
    id: n_z
    attributes:
      label: Number of Levels
      description: |
        Total number of vertical levels.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Number of vertical levels**
        
        Total grid cells in vertical.
        
        **Leave blank if:** Number varies (e.g., adaptive snow layers).
        
        </details>
      placeholder: "91"

  - type: input
    id: top_layer_thickness
    attributes:
      label: Top Layer Thickness (m)
      description: |
        Thickness of the uppermost layer in metres.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Uppermost layer thickness** (metres)
        
        Typical values:
        - Atmosphere: 10-100m
        - Ocean surface: 1-10m
        
        Provide nominal value if thickness varies.
        
        </details>
      placeholder: "2.0"

  - type: input
    id: bottom_layer_thickness
    attributes:
      label: Bottom Layer Thickness (m)
      description: |
        Thickness of the lowest layer in metres.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Lowest layer thickness** (metres)
        
        Typical values:
        - Atmosphere near-surface: 10-50m
        - Deep ocean: 100-500m
        
        **Leave blank if:** Layer is expandable (e.g., ice accumulation).
        
        </details>
      placeholder: "25.0"

  - type: input
    id: total_thickness
    attributes:
      label: Total Thickness (m)
      description: |
        Total vertical extent in metres.
        
        <details markdown="1">
        <summary>Detailed Guidance</summary>
        
        **Total vertical extent** (metres)
        
        Typical values:
        - Atmosphere: 30,000-85,000m (to stratosphere/mesosphere)
        - Ocean: 5,000-6,000m
        - Soil: 3-15m
        
        Provide nominal value if extent varies spatially.
        
        </details>
      placeholder: "80000"

  - type: markdown
    attributes:
      value: |
        ---
        
        ## Issue Handling
        
        **After submission:**
        - Creates `vertical_computational_grid` (v###)
        - Use this ID with a c### in Stage 3 (Model Component)
        - Track progress in issue comments

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: New submission or modification.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
