name: Vertical Grid Properties Documentation
description: Document vertical grid specifications as compound objects for EMD compliance.
title: "[EMD] Vertical Grid Properties"
labels: ['emd-submission', 'vertical-grid']
body:
  - type: markdown
    attributes:
      value: |
        # Vertical Grid Properties Documentation
        
        This template documents vertical grid specifications as compound objects referenced by model components. Based on EMD Section 4.2 requirements.

  - type: dropdown
    id: coordinate
    attributes:
      label: Coordinate
      description: |
        The coordinate type of the vertical grid.
        
        MANDATORY field from Coordinate CV.
      options:
        - "no-vertical-grid"
        - "air-potential-temperature"
        - "air-pressure"
        - "atmosphere-hybrid-height-coordinate"
        - "atmosphere-hybrid-sigma-pressure-coordinate"
        - "atmosphere-ln-pressure-coordinate"
        - "atmosphere-sigma-coordinate"
        - "atmosphere-sleve-coordinate"
        - "depth"
        - "geopotential-height"
        - "height"
        - "ocean-double-sigma-coordinate"
        - "ocean-s-coordinate-g1"
        - "ocean-s-coordinate-g2"
        - "ocean-s-coordinate"
        - "ocean-sigma-coordinate"
        - "ocean-sigma-z-coordinate"
        - "sea-water-potential-temperature"
        - "sea-water-pressure"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description (Optional)
      description: |
        Free-text description of the vertical grid.
        
        OPTIONAL field.
      placeholder: "Additional vertical grid details if needed"

  - type: input
    id: n_z
    attributes:
      label: N z
      description: |
        Number of grid cells in Z direction.
        
        OPTIONAL integer field. Must be omitted if n_z_range is set.
      placeholder: "e.g., 70"

  - type: input
    id: n_z_range
    attributes:
      label: N z Range
      description: |
        Minimum and maximum number of Z grid cells for variable resolution.
        
        OPTIONAL field as [integer,integer]. Must be omitted if n_z is set.
        
        Format: min, max
      placeholder: "e.g., 5, 15"

  - type: input
    id: bottom_layer_thickness
    attributes:
      label: Bottom Layer Thickness
      description: |
        Thickness of bottom model layer.
        
        OPTIONAL float field.
      placeholder: "e.g., 10.0"

  - type: input
    id: top_layer_thickness
    attributes:
      label: Top Layer Thickness
      description: |
        Thickness of top model layer.
        
        OPTIONAL float field.
      placeholder: "e.g., 10.0"

  - type: input
    id: top_of_model
    attributes:
      label: Top of Model
      description: |
        Value of upper boundary of top model layer.
        
        OPTIONAL float field.
      placeholder: "e.g., 85003.5"

  - type: dropdown
    id: vertical_units
    attributes:
      label: Vertical Units
      description: |
        Physical units for thickness and boundary values.
        
        OPTIONAL field - Required if any thickness/boundary values are set.
      options:
        - "K"
        - "m"
        - "Pa"

  - type: dropdown
    id: issue_category
    attributes:
      label: Issue Type
      description: This is pre-set and cannot be changed.
      options:
        - "vertical-grid"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "new"
        - "modify"
      default: 0
    validations:
      required: true
