name: Vertical Computational Grid Registration
description: Register a vertical computational grid
title: "[EMD] Vertical Computational Grid:"
labels: ['emd-submission', 'grid', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Vertical Computational Grid Registration
        
        Register a vertical computational grid.
        
        **This issue creates 1 entity:**
        - Vertical computational grid
        
        **Result:** Vertical grid ID (e.g., v100) to use when registering Model Components.
        
        **Note:** This is independent of horizontal grids - you can submit this in parallel with horizontal grid issues.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Description of this vertical grid.
        
        Include number of levels and vertical extent.
        
        Example: '85-level atmospheric hybrid height coordinate extending to approximately 85 km'
        
        <details markdown="1">
        <summary>Completion Guidance</summary>
        
        **Grid description** (from EMD specification):
        
        A description is only required if there is information that is not covered by any of the other properties.
        
        Some model components may have different and wholly independent vertical grids for different physical processes (e.g., a land surface model with soil, lake and snow sub-models). In such cases it may not be possible to provide some properties because a single value might not apply to all processes. When this happens, use the description property to record the relevant information for each physical process.
        
        **Include:**
        - Number of levels
        - Coordinate type
        - Vertical extent
        - Purpose (atmosphere, ocean, soil, ice)
        - Any non-standard features
        
        **Omit when:** All info covered by other properties
        
        </details>
      placeholder: "e.g., 75-level ocean depth coordinate from surface to 5500m"
    validations:
      required: true

  - type: dropdown
    id: vertical_coordinate
    attributes:
      label: Vertical Coordinate
      description: |
        Coordinate type.
        
        Common:
        - **atmosphere-hybrid-height-coordinate**: Atmosphere height-based
        - **atmosphere-hybrid-sigma-pressure-coordinate**: Atmosphere pressure-based
        - **depth**: Ocean/soil depth
        - **ocean-s-coordinate**: Ocean stretched
        - **land-ice-sigma-coordinate**: Ice sheets
        
        <details markdown="1">
        <summary>Completion Guidance</summary>
        
        **Vertical coordinate types** (from EMD vertical_coordinate CV):
        
        The coordinate type of the vertical grid.
        
        **Atmosphere options:**
        - **atmosphere_hybrid_height_coordinate**: Terrain-following near surface, flat at top (common)
        - **atmosphere_hybrid_sigma_pressure_coordinate**: Sigma near surface, pressure at top
        - **atmosphere_sigma_coordinate**: Pure terrain-following sigma
        - **height**: Height above reference surface
        
        **Ocean options:**
        - **depth**: Standard z-levels from surface (most common)
        - **ocean_s_coordinate**: Stretched vertical (high resolution near surface)
        - **ocean_sigma_z_coordinate**: Hybrid sigma-z coordinate
        - **ocean_sigma_coordinate**: Pure sigma (terrain-following)
        
        **Land/Ice options:**
        - **depth**: Soil layers below surface
        - **land_ice_sigma_coordinate**: Ice sheet layers
        - **height**: Above ground height
        
        **Omit if:** Different physical processes have grids with different vertical coordinate types (note this in description instead)
        
        </details>
      options:
        - "Not specified"
        - "air_potential_temperature"
        - "air_pressure"
        - "atmosphere_hybrid_height_coordinate"
        - "atmosphere_hybrid_sigma_pressure_coordinate"
        - "atmosphere_ln_pressure_coordinate"
        - "atmosphere_sigma_coordinate"
        - "atmosphere_sleve_coordinate"
        - "depth"
        - "geopotential_height"
        - "height"
        - "land_ice_sigma_coordinate"
        - "ocean_double_sigma_coordinate"
        - "ocean_s_coordinate_g1"
        - "ocean_s_coordinate_g2"
        - "ocean_s_coordinate"
        - "ocean_sigma_coordinate"
        - "ocean_sigma_z_coordinate"
        - "sea_water_potential_temperature"
        - "sea_water_pressure"
        - "z*"
      default: 0
    validations:
      required: true

  - type: input
    id: n_z
    attributes:
      label: Number of Layers
      description: |
        Number of vertical layers (grid cells).
        
        Leave blank if varies across processes.
        
        <details markdown="1">
        <summary>Completion Guidance</summary>
        
        **Number of layers** (from EMD specification):
        
        The number of layers (mass points) in the vertical grid.
        
        **Typical values:**
        
        **Atmosphere:**
        - Low-top models: 30-50 levels (~30km)
        - Mid-top models: 50-80 levels (~50-60km)
        - High-top models: 80-150 levels (~80-150km)
        
        **Ocean:**
        - Standard: 40-50 levels (~5000m)
        - High-resolution: 60-75 levels
        
        **Land/Ice:**
        - Soil: 3-15 layers
        - Ice sheets: 5-20 layers
        
        **Leave blank if:**
        - Varies across domain
        - Adaptive mesh
        - Different for different processes
        
        </details>
      placeholder: "e.g., 85"

  - type: input
    id: n_z_range
    attributes:
      label: Layer Range
      description: |
        Min and max layers if variable.
        
        Format: min,max
        
        Leave blank if n_z is provided.
      placeholder: "e.g., 5,15"

  - type: input
    id: top_layer_thickness
    attributes:
      label: Top Layer Thickness (m)
      description: |
        Thickness of top layer in metres.
        
        Provide nominal/representative if varies.
        
        <details markdown="1">
        <summary>Completion Guidance</summary>
        
        **Top layer thickness** (from EMD specification):
        
        The thickness of the uppermost layer, in metres.
        
        **Typical values:**
        
        **Atmosphere:**
        - Near surface: 10-50m
        - At model top: 500-2000m (increases with height)
        
        **Ocean:**
        - Surface layer: 1-10m
        
        **Land surface:**
        - Top soil layer: 0.01-0.1m
        
        **Ice:**
        - Top layer: 0.04m (from BISICLES example)
        
        **Provide representative value if varies.**
        
        **Note:** For atmosphere, this typically refers to the layer nearest the surface. For ocean, this is the surface layer.
        
        </details>
      placeholder: "e.g., 10.0"

  - type: input
    id: bottom_layer_thickness
    attributes:
      label: Bottom Layer Thickness (m)
      description: |
        Thickness of bottom layer in metres.
        
        Provide nominal/representative if varies.
        
        Leave blank if expandable (e.g., ice accumulation).
        
        <details markdown="1">
        <summary>Completion Guidance</summary>
        
        **Bottom layer thickness** (from EMD specification):
        
        The thickness of the lowermost layer, in metres.
        
        **Typical values:**
        
        **Atmosphere:**
        - Model top layer: 1000-5000m
        
        **Ocean:**
        - Bottom layer: 200-500m
        
        **Leave blank if:**
        - Layer can expand (e.g., ice accumulation)
        - Thickness not well-defined
        
        **From EMD example (BISICLES):** 'The bottom level of the snowpack, which starts 6 metres below the snow surface, expands in thickness to hold as much mass as the column accumulates.'
        
        </details>
      placeholder: "e.g., 100.0"

  - type: input
    id: total_thickness
    attributes:
      label: Total Thickness (m)
      description: |
        Total vertical extent in metres.
        
        Provide nominal/representative if varies.
        
        <details markdown="1">
        <summary>Completion Guidance</summary>
        
        **Total vertical extent** (from EMD specification):
        
        The total thickness of all layers combined, in metres.
        
        **Typical values:**
        
        **Atmosphere:**
        - Low-top: ~30,000m (30km)
        - Mid-top: ~50,000-61,000m (50-61km)
        - High-top: ~80,000-150,000m (80-150km)
        - Example: 84763.34m (from EMD)
        
        **Ocean:**
        - Standard: ~4,000-6,000m
        - Deep ocean: up to 11,000m
        
        **Ice sheets:**
        - Greenland: up to 3,000m
        - Antarctica: up to 4,500m
        
        **Soil:**
        - Typically 3-10m depth
        
        </details>
      placeholder: "e.g., 84763.34"

  - type: markdown
    attributes:
      value: |
        ## What Will Be Generated
        
        This issue creates:
        
        **vertical_computational_grid** (ID: v###)
        - Contains: Coordinate type, number of layers, thicknesses
        
        **You'll receive:** Vertical grid ID (v###)
        
        **Next:** Use this ID + horizontal grid ID (c###) in Model Component issue.

  - type: markdown
    attributes:
      value: |
        ## Issue Handling Metadata

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
