name: "Add/Modify: Vertical Computational Grid"
description: Register a vertical computational grid
title: "Add/Modify: Vertical Computational Grid: <Type grid ID here>"
labels: ['emd-submission', 'vertical-grid', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Vertical Computational Grid Registration
        
        Register a vertical computational grid definition.
        
        Defines the vertical layer structure for a model component.
        
        Vertical grid IDs follow format: v[NNN] (e.g., v100, v101)

  - type: input
    id: id
    attributes:
      label: Grid ID
      description: |
        Unique identifier for this vertical grid.
        
        Format: v[NNN] where NNN is a number.
      placeholder: "e.g., v100, v101, v102"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Description to distinguish this vertical grid.
        
        Include key characteristics like number of levels and extent.
      placeholder: "e.g., 85-level atmospheric hybrid height coordinate extending to approximately 85 km"
    validations:
      required: true

  - type: dropdown
    id: vertical_coordinate
    attributes:
      label: Vertical Coordinate
      description: |
        Coordinate type for the vertical grid.
        
        - atmosphere-hybrid-height-coordinate: Height-based hybrid
        - atmosphere-hybrid-sigma-pressure-coordinate: Pressure-based hybrid
        - atmosphere-sigma-coordinate: Terrain-following sigma
        - depth: Ocean/soil depth
        - height: Geometric height
        - land-ice-sigma-coordinate: Ice sheet sigma
        - ocean-s-coordinate: Ocean stretched coordinate
        - ocean-sigma-z-coordinate: Ocean sigma-z hybrid
      options:
        - "air_potential_temperature"
        - "air_pressure"
        - "atmosphere_hybrid_height_coordinate"
        - "atmosphere_hybrid_sigma_pressure_coordinate"
        - "atmosphere_ln_pressure_coordinate"
        - "atmosphere_sigma_coordinate"
        - "atmosphere_sleve_coordinate"
        - "depth"
        - "geopotential_height"
        - "height"
        - "land_ice_sigma_coordinate"
        - "ocean_double_sigma_coordinate"
        - "ocean_s_coordinate"
        - "ocean_s_coordinate_g1"
        - "ocean_s_coordinate_g2"
        - "ocean_sigma_coordinate"
        - "ocean_sigma_z_coordinate"
        - "sea_water_potential_temperature"
        - "sea_water_pressure"
        - "z*"
    validations:
      required: true

  - type: input
    id: n_z
    attributes:
      label: Number of Layers
      description: |
        Number of mass layers (grid cells) in the vertical.
        
        Leave blank if varies across physical processes or grid.
      placeholder: "e.g., 85"

  - type: input
    id: n_z_range
    attributes:
      label: Layer Range
      description: |
        Min and max layers if variable.
        
        Format: min,max
        
        Leave blank if n_z is provided or not applicable.
      placeholder: "e.g., 5,15"

  - type: input
    id: top_layer_thickness
    attributes:
      label: Top Layer Thickness
      description: |
        Thickness of the top model layer in metres.
        
        Provide nominal/representative maximum if varies.
      placeholder: "e.g., 10.0"

  - type: input
    id: bottom_layer_thickness
    attributes:
      label: Bottom Layer Thickness
      description: |
        Thickness of the bottom model layer in metres.
        
        Provide nominal/representative maximum if varies.
        
        Leave blank if layer can expand (e.g., ice accumulation).
      placeholder: "e.g., 100.0"

  - type: input
    id: total_thickness
    attributes:
      label: Total Thickness
      description: |
        Total thickness spanned by all layers in metres.
        
        Provide nominal/representative maximum if varies.
      placeholder: "e.g., 84763.34"

  - type: markdown
    attributes:
      value: |
        ## Issue Handling Metadata

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
