name: → workflows

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      # - '.github/workflows/**'
      # - '.github/CONTRIBUTING.md'
      # - '.github/prepublish/**'
      # - '.github/GENERATE_SUMMARIES/**'

  workflow_dispatch:

permissions:
  contents: write

# ============================================================
# CONFIGURATION: Define what to sync from main to other branches
# ============================================================
env:
  # Folders to sync (space-separated)
  # Excluded: ISSUE_TEMPLATE, GEN_ISSUE_TEMPLATE
  SYNC_FOLDERS: "workflows prepublish GENERATE_SUMMARIES"
  
  # Individual files to sync (space-separated, relative to .github/)
  SYNC_FILES: "CONTRIBUTING.md"

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: 
          - src-data
          - docs
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Fetch main branch
        run: git fetch origin main --depth=1 || true

      - name: Sync folders from main
        run: |
          for folder in $SYNC_FOLDERS; do
            echo "Syncing folder: .github/$folder"
            mkdir -p ".github/$folder"
            git checkout origin/main -- ".github/$folder/" 2>/dev/null || \
              echo "  ⚠ Folder .github/$folder not found on main, skipping"
          done

      - name: Sync files from main
        run: |
          for file in $SYNC_FILES; do
            echo "Syncing file: .github/$file"
            if git cat-file -e "origin/main:.github/$file" 2>/dev/null; then
              git checkout origin/main -- ".github/$file"
            else
              echo "  ⚠ File .github/$file not found on main, skipping"
            fi
          done
      
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: '.github/'
          author_name: 'cmip-ipo'
          author_email: 'actions@wcrp-cmip.org'
          message: 'Sync .github files from main'
          push: true
